'use strict';
const M=window.InitModel,$=id=>document.getElementById(id),fmt=(n)=>n===0?'0':Math.abs(n)<.001||Math.abs(n)>=1e4?n.toExponential(2):n.toFixed(3),number=id=>Number($(id).value);
const storageKey='initialization-lab-v1';let answers={};
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))answers=saved;}catch{$('storage-note').textContent='Progress is available for this visit; browser storage is unavailable.';}
const quizzes=[
 [{id:'s-theory',kind:'CONCEPT CHECK',question:'Why do zero biases fail to break symmetry when all hidden weights are also zero?',options:['Biases never receive gradients.','Uniform biases give every unit the same preactivation.','Biases only affect the output layer.','Biases become random after one update.'],correct:1,explain:'With W = 0, each preactivation is just bᵢ. Equal biases give equal activations. Random weights can break symmetry even when all biases start at zero.',hint:'Write zᵢ = ΣⱼWᵢⱼxⱼ + bᵢ.',wrong:['Biases do receive gradients: ∂L/∂bᵢ = δᵢ.','', 'Biases can appear in every hidden layer.','A deterministic update does not introduce randomness.']},
 {id:'s-number',kind:'NUMERICAL CHECK',question:'For x = [1, 2] and δ = [0.5, 0.5, 0.5], what are ∂L/∂W₁₁ and ∂L/∂W₂₁?',options:['1.0 and 0.5','0.5 and 0.5','0 and 0','0.25 and 0.5'],correct:1,explain:'Both use the first input: δ₁x₁ = δ₂x₁ = 0.5 × 1 = 0.5. The second column would instead contain 1.0.',hint:'∂L/∂Wᵢⱼ = δᵢxⱼ. The column index chooses the input.',wrong:['Both requested weights connect to x₁, not x₂.','','Zero weights do not make this supplied gradient zero.','Use δᵢx₁; there is no extra factor of 0.5.']}],
 [{id:'r-theory',kind:'CONCEPT CHECK',question:'What happens to the local tanh derivative when its input saturates near a large positive or negative value?',options:['It grows without bound.','It approaches zero.','It stays exactly one.','It alternates randomly between −1 and 1.'],correct:1,explain:'tanh′(z) = 1 − tanh²(z). When tanh(z) approaches ±1, its derivative approaches zero, suppressing that local gradient factor.',hint:'Evaluate 1 − tanh²(z) when tanh(z) ≈ ±1.',wrong:['The derivative is bounded between zero and one.','','The derivative is one at zero, not at saturation.','The derivative is nonnegative and deterministic.']},
 {id:'r-number',kind:'NUMERICAL CHECK',question:'A linear layer has fan-in 64, independent centered unit-variance inputs, and weights N(0, 1). What is Var(z)?',options:['1','8','64','4096'],correct:2,explain:'Var(z) = nᵢₙ Var(w) Var(x) = 64 × 1 × 1 = 64.',hint:'Each of the 64 independent terms contributes variance 1.',wrong:['Summing 64 independent terms adds their variances.','8 is the standard deviation, not the variance.','','Variances add here; you do not square the fan-in.']}],
 [{id:'x-theory',kind:'CONCEPT CHECK',question:'Why does gain-1 Xavier initialization lose signal energy in an equal-width ReLU network?',options:['ReLU doubles every negative input.','ReLU removes half the second moment of symmetric preactivations.','ReLU is non-differentiable everywhere.','Xavier gives every neuron identical weights.'],correct:1,explain:'For symmetric z, E[ReLU(z)²] = E[z²]/2. Gain-1 Xavier at equal widths does not compensate for that factor.',hint:'Think about the squared signal on each side of zero.',wrong:['ReLU sets negative inputs to zero.','','ReLU has a derivative away from zero.','Xavier uses random weights; the issue is scale, not symmetry.']},
 {id:'x-number',kind:'NUMERICAL CHECK',question:'For Xavier normal with fan-in 256 and fan-out 512, what is the weight standard deviation?',options:['0.0884','0.0510','0.00260','0.00130'],correct:1,explain:'σ = √(2/(256 + 512)) = √(2/768) ≈ 0.0510. The value 0.00260 is the variance.',hint:'Take the square root after adding the two widths.',wrong:['That is √(2/256), the ReLU He scale for this fan-in.','','That is the variance; the question asks for standard deviation.','Use 2/(fan-in + fan-out), then take a square root.']}],
 [{id:'h-theory',kind:'CONCEPT CHECK',question:'Leaky ReLU has negative slope α = 0.1. Which weight variance preserves the expected forward second moment?',options:['2/nᵢₙ','2/((1 + α²)nᵢₙ)','2α/nᵢₙ','1/((1 − α)nᵢₙ)'],correct:1,explain:'The negative half contributes α² of its original squared signal. The retained fraction is (1 + α²)/2, so the weight variance compensates with 2/((1 + α²)nᵢₙ).',hint:'The quantity being propagated is squared, so α becomes α².',wrong:['That is exact for α = 0, the ordinary ReLU case.','','The contribution depends on α² and includes the positive half.','The derivation uses the second moment from both halves.']},
 {id:'h-number',kind:'NUMERICAL CHECK',question:'At fan-in = fan-out = 100, what is the ratio Var(He weights) / Var(Xavier weights)?',options:['0.5','1','2','4'],correct:2,explain:'He gives 2/100 = 0.02; Xavier gives 2/200 = 0.01. The ratio is 2.',hint:'These are variances, not standard deviations.',wrong:['That is the inverse ratio.','He includes a factor of two for ReLU.','','The variance doubles; it is not squared again.']}],
 [{id:'d-case',kind:'DIAGNOSIS',question:'Which diagnosis and intervention best fit this controlled case?',options:['Exploding gradients → set every weight to 1.','Signal decay from the ReLU/Xavier mismatch → use He initialization.','Symmetry lock → increase the learning rate tenfold.','Overfitting → add more weight decay.'],correct:1,explain:'ReLU halves the expected second moment at each equal-width layer under gain-1 Xavier. He compensates for this factor. In a real model, verify the diagnosis with activation and gradient measurements.',hint:'Match the activation to the initializer’s derivation.',wrong:['The gradients are tiny, and constant hidden weights create symmetry.','','Random Xavier weights already break symmetry.','This symptom appears immediately, before evidence of overfitting.']},
 {id:'d-number',kind:'TRANSFER CHECK',question:'In the simplified equal-width ReLU/Xavier model, what is q₁₀ / q₀?',options:['10','1','2⁻¹⁰ ≈ 0.000977','2¹⁰ = 1024'],correct:2,explain:'The recurrence is qℓ = ½qℓ₋₁, so ten layers give (½)¹⁰ ≈ 0.000977.',hint:'Multiply the per-layer factor ten times.',wrong:['The factor compounds multiplicatively.','That would require compensation such as He.','','ReLU/Xavier decreases the second moment in this model.']},
 {id:'d-transfer',kind:'FINAL CHECK',question:'You replace every ReLU with a linear activation but keep He initialization. What does the equal-width model predict?',options:['q doubles at each layer.','q stays fixed.','Every neuron becomes identical.','q is always zero.'],correct:0,explain:'He gives n Var(w) = 2. A linear activation does not remove half the second moment, so q doubles per layer. Revisit the scale whenever you change the activation.',hint:'Linear activation no longer discards the negative half.',wrong:['','The factor of two is now uncompensated.','Random He weights still break symmetry.','Random weights and nonzero input energy do not force q to zero.']}]
];
const allQuestions=quizzes.flat();answers=Object.fromEntries(Object.entries(answers).filter(([id,value])=>allQuestions.some(q=>q.id===id&&Number.isInteger(value)&&value>=0&&value<q.options.length)));
function save(){try{localStorage.setItem(storageKey,JSON.stringify(answers));}catch{$('storage-note').textContent='Progress is available for this visit; browser storage is unavailable.';}}
function renderQuestion(q,container){const article=document.createElement('article');article.className='question';article.innerHTML=`<div class="q-label">${q.kind}</div><h3 id="${q.id}-title">${q.question}</h3><div class="answers" role="group" aria-labelledby="${q.id}-title"></div><div id="${q.id}-feedback" aria-live="polite"></div><details class="hint"><summary>Need a hint?</summary><p>${q.hint}</p></details>`;q.options.forEach((option,i)=>{const button=document.createElement('button');button.className='answer';button.innerHTML=`<span class="letter">${'ABCD'[i]}</span><span>${option}</span>`;button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{answers[q.id]=i;save();paintQuestion(q,article);updateProgress();});article.querySelector('.answers').appendChild(button);});container.appendChild(article);paintQuestion(q,article);}
function paintQuestion(q,article){const choice=answers[q.id],feedback=article.querySelector('[aria-live]');article.querySelectorAll('.answer').forEach((b,i)=>{b.className='answer'+(choice===i?(i===q.correct?' correct':' wrong'):'');b.setAttribute('aria-pressed',String(choice===i));});feedback.innerHTML=choice===undefined?'':`<p class="feedback ${choice===q.correct?'success':''}"><strong>${choice===q.correct?'Correct.':'Try again.'}</strong> ${choice===q.correct?q.explain:q.wrong[choice]}</p>`;}
function updateProgress(){const correct=allQuestions.filter(q=>answers[q.id]===q.correct).length;let complete=0;quizzes.forEach((list,i)=>{const done=list.every(q=>answers[q.id]===q.correct);if(done)complete++;document.querySelector(`[data-section="${i}"]`).classList.toggle('complete',done);document.querySelectorAll('nav a')[i].classList.toggle('done',done);});$('progress').value=correct;$('progress-label').textContent=`${complete} of 5 sections complete`;$('progress-percent').textContent=Math.round(correct/11*100)+'%';$('finish').hidden=complete!==5;}
quizzes.forEach((list,i)=>list.forEach(q=>renderQuestion(q,document.querySelector(`[data-quiz="${i}"]`))));updateProgress();
$('reset-progress').addEventListener('click',()=>$('reset-dialog').showModal());$('cancel-reset').addEventListener('click',()=>$('reset-dialog').close());$('confirm-reset').addEventListener('click',()=>{answers={};save();allQuestions.forEach(q=>paintQuestion(q,$(`${q.id}-title`).closest('article')));updateProgress();$('reset-dialog').close();});$('print').addEventListener('click',()=>window.print());
const navLinks=[...document.querySelectorAll('nav a')],sections=[...document.querySelectorAll('.lab')];let scrollPending=false;window.addEventListener('scroll',()=>{if(scrollPending)return;scrollPending=true;requestAnimationFrame(()=>{let active=0;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<220)active=i;});navLinks.forEach((link,i)=>{link.classList.toggle('active',i===active);if(i===active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});scrollPending=false;});},{passive:true});

// Small software 3D renderer: actual xyz geometry, orbit camera, projected meshes and particles.
// No external runtime or network request is required for any experiment.
const colors={teal:'#167569',orange:'#c0613e',gold:'#bc8730',ink:'#294c42',grid:'#cbd6c6'};
class Scene{
 constructor(id,type){this.canvas=$(id);this.ctx=this.canvas.getContext('2d');this.type=type;this.yaw=-.62;this.pitch=.68;this.phase=0;this.playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;this.visible=true;this.data={};this.last=0;this.width=600;this.height=300;this.down=null;this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(this.canvas);this.observer=new IntersectionObserver(es=>{this.visible=es[0].isIntersecting;});this.observer.observe(this.canvas);this.canvas.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY];this.canvas.setPointerCapture(e.pointerId);});this.canvas.addEventListener('pointermove',e=>{if(!this.down)return;this.yaw+=(e.clientX-this.down[0])*.008;this.pitch=Math.max(.2,Math.min(1.35,this.pitch+(e.clientY-this.down[1])*.006));this.down=[e.clientX,e.clientY];this.draw();});for(const ev of ['pointerup','pointercancel'])this.canvas.addEventListener(ev,()=>this.down=null);this.canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();this.yaw+=e.key==='ArrowLeft'?-.12:e.key==='ArrowRight'?.12:0;this.pitch=Math.max(.2,Math.min(1.35,this.pitch+(e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0)));this.draw();});}
 point(x,y,z){const a=this.yaw,b=this.pitch,rx=x*Math.cos(a)-y*Math.sin(a),ry=x*Math.sin(a)+y*Math.cos(a),rz=z;const sy=ry*Math.sin(b)+rz*Math.cos(b),depth=-ry*Math.cos(b)+rz*Math.sin(b);const perspective=18/(18-depth),scale=Math.min(this.width/12.4,this.height/7.6);return [this.width/2+rx*scale*perspective,this.height*.6-sy*scale*perspective,depth,scale*perspective];}
 line(points,color=colors.grid,width=1){const ctx=this.ctx;ctx.beginPath();points.forEach((p,i)=>{const t=this.point(...p);i?ctx.lineTo(t[0],t[1]):ctx.moveTo(t[0],t[1]);});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
 polygon(points,fill,stroke){const ctx=this.ctx;ctx.beginPath();points.forEach((p,i)=>{const t=this.point(...p);i?ctx.lineTo(t[0],t[1]):ctx.moveTo(t[0],t[1]);});ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.6;ctx.stroke();}}
 sphere(x,y,z,color,r=.14){const [px,py,,scale]=this.point(x,y,z),ctx=this.ctx,rad=Math.max(2,r*scale);ctx.beginPath();ctx.ellipse(px,py+rad*.65,rad*1.2,rad*.33,0,0,Math.PI*2);ctx.fillStyle='#183f2920';ctx.fill();const g=ctx.createRadialGradient(px-rad*.33,py-rad*.4,rad*.05,px,py,rad);g.addColorStop(0,'#fff9dc');g.addColorStop(.28,color);g.addColorStop(1,color);ctx.fillStyle=g;ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.fill();}
 label(text,x,y,z,color=colors.ink){const p=this.point(x,y,z);this.ctx.fillStyle=color;this.ctx.font='11px monospace';this.ctx.fillText(text,p[0],p[1]);}
 surface(fn){const cells=[];for(let y=-4;y<4;y+=.5)for(let x=-4;x<4;x+=.5){const pts=[[x,y,fn(x,y)],[x+.5,y,fn(x+.5,y)],[x+.5,y+.5,fn(x+.5,y+.5)],[x,y+.5,fn(x,y+.5)]],depth=pts.reduce((s,p)=>s+this.point(...p)[2],0)/4;cells.push({pts,depth,x,y});}cells.sort((a,b)=>a.depth-b.depth);for(const c of cells)this.polygon(c.pts,((c.x+c.y)*2)%2?'#dce7dacc':'#e5eddfcc','#b8cdb68a');}
 draw(){if(!this.ctx)return;const rect=this.canvas.getBoundingClientRect();if(!rect.width)return;this.width=rect.width;this.height=rect.height;const dpr=Math.min(devicePixelRatio||1,2);if(this.canvas.width!==Math.round(rect.width*dpr)||this.canvas.height!==Math.round(rect.height*dpr)){this.canvas.width=Math.round(rect.width*dpr);this.canvas.height=Math.round(rect.height*dpr);}const ctx=this.ctx;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,this.width,this.height);const bg=ctx.createLinearGradient(0,0,0,this.height);bg.addColorStop(0,'#f3f4eb');bg.addColorStop(1,'#e7edde');ctx.fillStyle=bg;ctx.fillRect(0,0,this.width,this.height);if(this.type==='xavier'){this.distributions();return;}const t=this.phase,terrain=(x,y)=>.2+.42*Math.sin(x*2.1)*Math.cos(y*1.8)+.22*Math.sin(x*3+y*2.6);const fn=this.type==='he'?(x,y)=>.09*(x*x+y*y):this.type==='random'?terrain:()=>0;this.surface(fn);
 if(this.type==='symmetry'){
  const separate=this.data.perturb;for(let i=0;i<5;i++){const spread=separate?(i-2)*.7:0,pts=[];for(let j=0;j<=40;j++){const u=j/40;pts.push([-3+u*6,spread*u,.1]);}this.line(pts,separate?[colors.teal,colors.orange,colors.gold,'#6c77a4','#467e51'][i]:colors.orange,separate?1.8:3);}
  for(let i=0;i<5;i++){const u=Math.min(1,t),spread=separate?(i-2)*.7:0;this.sphere(-3+6*u,spread*u,.18,separate?[colors.teal,colors.orange,colors.gold,'#6c77a4','#467e51'][i]:colors.orange,.18);}
  this.label(separate?'5 distinct paths':'5 overlapping neurons',-3,-3.5,0);this.label('weight direction',1.2,4,0);
 }else if(this.type==='he'){
  const vanish=this.data.init==='xavier',r=3.4*(1-Math.min(t,1)*.96);for(let i=0;i<8;i++){const a=i*Math.PI/4,pts=[];for(let j=0;j<35;j++){const d=3.4-j/34*3.27;pts.push([Math.cos(a)*d,Math.sin(a)*d,.09*d*d+.03]);}this.line(pts,vanish?'#c0613e85':'#16756990',1.5);const x=Math.cos(a)*r,y=Math.sin(a)*r;this.sphere(x,y,fn(x,y)+.14,vanish?colors.orange:colors.teal,vanish?.17*(1-Math.min(t,1)*.8):.17);}this.label(vanish?'signal fades with depth':'balanced scale',-3.8,-3.6,0);
 }else{
  const scale=this.data.scale||1,u=Math.min(t,1);for(let i=0;i<10;i++){let a=i*2.4,x=Math.cos(a)*2.8,y=Math.sin(a)*2.8,z=fn(x,y)+.16;
   if(i<4){const d=Math.min(2.5,Math.max(.08,scale))*u;x+=Math.cos(a)*d;y+=Math.sin(a)*d;z+=d*.8;}
   else if(i<8){x*=1-u*.35;y*=1-u*.35;z=fn(x,y)+.15;}
   this.sphere(x,y,z,colors.gold,.14);}
  this.label('uneven starts / uneven signals',-3.9,-3.7,0);
 }
 ctx.fillStyle='#607661';ctx.font='10px monospace';ctx.fillText(this.type==='symmetry'?'SYMMETRY STUDY':this.type==='he'?'z = 0.09(x² + y²)':'SCALE STUDY',15,22);
 }
 distributions(){const rows=this.data.rows;if(!rows)return;for(let n=-4;n<=4;n++)this.line([[-4,n,0],[4,n,0]],'#c9d5c3');for(let x=-4;x<=4;x++)this.line([[x,-4,0],[x,4,0]],'#c9d5c3');const depth=rows.length-1,indices=[0,Math.max(1,Math.round(depth*.25)),Math.max(1,Math.round(depth*.5)),Math.max(1,Math.round(depth*.75)),depth];const normals=M.normalSamples(19,4000),activation=this.data.activation;const ridges=indices.map((index,k)=>{const row=rows[index],bin=new Array(49).fill(0);for(const n of normals){const value=index===0?n:M.activate(n*Math.sqrt(row.preVariance),activation);const b=Math.max(0,Math.min(48,Math.floor((value+3.2)/6.4*49)));bin[b]++;}return {index,k,bin,depth:this.point(0,-3.2+k*1.6,0)[2]};}).sort((a,b)=>a.depth-b.depth);for(const r of ridges){const y=-3.2+r.k*1.6,max=Math.max(...r.bin),points=r.bin.map((v,i)=>[-3.2+i/48*6.4,y,v/max*1.55]);const active=Math.round(Math.min(1,this.phase)*4)===r.k;this.polygon([[-3.2,y,0],...points,[3.2,y,0]],active?'#d9a06065':'#75a78b25',active?colors.orange:colors.teal);this.line(points,active?colors.orange:colors.teal,active?2.8:1.1);this.label('L'+r.index,3.45,y,0);}this.sphere(0,-3.2+Math.min(1,this.phase)*6.4,.15,colors.orange,.18);this.label('−3',-3.2,4.1,0);this.label('0',0,4.1,0);this.label('+3',3.2,4.1,0);this.ctx.fillStyle='#607661';this.ctx.font='10px monospace';this.ctx.fillText('ACTIVATION VALUES · PEAK-NORMALIZED RIDGES',13,22);}
}
const scenes={symmetry:new Scene('scene-symmetry','symmetry'),random:new Scene('scene-random','random'),xavier:new Scene('scene-xavier','xavier'),he:new Scene('scene-he','he')};
document.querySelectorAll('[data-motion]').forEach(b=>{const s=scenes[b.dataset.motion];b.textContent=s.playing?'Pause':'Play';b.setAttribute('aria-pressed',String(s.playing));b.addEventListener('click',()=>{s.playing=!s.playing;b.textContent=s.playing?'Pause':'Play';b.setAttribute('aria-pressed',String(s.playing));});});document.querySelectorAll('[data-replay]').forEach(b=>b.addEventListener('click',()=>{const s=scenes[b.dataset.replay];s.phase=0;s.yaw=-.62;s.pitch=.68;s.draw();}));
let lastTime=0;function animate(time){const elapsed=Math.min(.05,(time-lastTime)/1000);lastTime=time;for(const scene of Object.values(scenes)){if(scene.playing&&scene.visible&&!document.hidden){scene.phase+=elapsed*(scene.speed||1)/12;if(scene.phase>1.15)scene.phase=0;scene.draw();updateWalkthrough(scene);}}requestAnimationFrame(animate);}requestAnimationFrame(animate);
function metric(label,value){return `<div><small>${label}</small><b>${value}</b></div>`;}
function status(id,title,body,warn=false){$(id).className='status'+(warn?' warn':'');$(id).innerHTML=`<strong>${title}</strong>${body}`;}
function chart(id,series,subtitle){const W=520,H=188,p={l:55,r:16,t:17,b:35},maxDepth=series[0].rows.length-1;const logs=series.flatMap(s=>s.rows.map(r=>Math.log10(Math.max(r.q,1e-100))));let low=Math.floor(Math.min(-.25,...logs)),high=Math.ceil(Math.max(.25,...logs));if(high-low<2){low=-1;high=1;}const x=i=>p.l+i/maxDepth*(W-p.l-p.r),y=q=>H-p.b-(Math.log10(Math.max(q,1e-100))-low)/(high-low)*(H-p.t-p.b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${subtitle}. Logarithmic vertical axis. Exact layer values follow below."><title>${subtitle}</title>`;for(let j=0;j<=4;j++){const exponent=low+(high-low)*j/4,py=y(10**exponent);svg+=`<line x1="${p.l}" y1="${py}" x2="${W-p.r}" y2="${py}" stroke="#dce1d5"/><text x="${p.l-8}" y="${py+4}" text-anchor="end" font-size="10" font-family="monospace" fill="#637163">10^${exponent.toFixed(exponent%1?1:0)}</text>`;}svg+=`<line x1="${p.l}" y1="${y(1)}" x2="${W-p.r}" y2="${y(1)}" stroke="#829b7c" stroke-dasharray="4 4"/>`;for(const i of [0,Math.round(maxDepth/2),maxDepth])svg+=`<text x="${x(i)}" y="${H-15}" text-anchor="middle" font-size="11" fill="#637163" font-family="monospace">${i}</text>`;series.forEach(s=>{const path=s.rows.map((r,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(r.q).toFixed(2)}`).join(' ');svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2.4"/><circle cx="${x(maxDepth)}" cy="${y(s.rows.at(-1).q)}" r="3.5" fill="${s.color}"/>`;});svg+=`<text x="${W/2}" y="${H-1}" text-anchor="middle" font-size="10" fill="#637163" font-family="monospace">LAYER</text></svg>`;
 const wasOpen=$(id).querySelector('details')?.open;$(id).innerHTML=`<div class="chart-legend">${series.map(s=>`<span class="${s.color===colors.orange?'coral':''}">${s.name}</span>`).join('')}</div>${svg}<p class="chart-caption">q = E[a²] · logarithmic scale · dashed reference q = 1</p><details class="hint" ${wasOpen?'open':''}><summary>Read exact layer statistics</summary><div style="overflow:auto;max-height:260px"><table><caption class="sr-table-caption">${subtitle}</caption><thead><tr><th>Layer</th>${series.map(s=>`<th>${s.name} · q</th>`).join('')}<th>Var(a)*</th></tr></thead><tbody>${series[0].rows.map((r,i)=>`<tr><td>${i}</td>${series.map(s=>`<td>${fmt(s.rows[i].q)}</td>`).join('')}<td>${fmt(r.variance)}</td></tr>`).join('')}</tbody></table><p class="chart-caption">*Centered activation variance for ${series[0].name}.</p></div></details>`;
}
function updateSymmetry(){const c=number('sym-init'),depth=number('sym-depth'),perturb=$('sym-break').checked,rows=M.symmetry(c,depth,perturb),last=rows.at(-1);$('sym-depth-value').textContent=depth+' layers';$('symmetry-bars').innerHTML=last.map((v,i)=>`<div><small>UNIT ${i+1}</small><b>${Math.abs(v)<1e-4&&v!==0?v.toExponential(1):v.toFixed(3)}</b><span class="mini-bar" style="width:${Math.abs(v)*90}%"></span></div>`).join('');status('sym-status',perturb?'Symmetry can break':'Symmetry locked',perturb?(c===2?'The weights differ, but c = 2 can still saturate tanh. Breaking symmetry alone does not solve scale.':'Distinct weights allow different features. A small random scale can still make the signal fade with depth.'):'All five hidden units have identical outputs. A wider layer still computes repeated features.',!perturb||c===2);scenes.symmetry.data={perturb,depth,rows};scenes.symmetry.draw();}
function updateRandom(){const sigma=10**number('random-sigma'),activation=$('random-activation').value,depth=number('random-depth'),width=number('random-width'),result=M.propagate({init:'random',activation,sigma,nIn:width,nOut:width,depth}),last=result.rows.at(-1);$('random-sigma-value').textContent=sigma.toFixed(3);$('random-depth-value').textContent=depth+' layers';$('random-metrics').innerHTML=metric('Final q',fmt(last.q))+metric('n × σ²',fmt(width*sigma*sigma));if(activation==='tanh'&&last.saturation>.25)status('random-status','tanh is saturated',`${(last.saturation*100).toFixed(1)}% of modeled final preactivations give |tanh(z)| > 0.95. Outputs remain in [−1, 1].`,true);else if(last.q>10)status('random-status','Signal is growing',`The final second moment is ${fmt(last.q)} times the input value.`,true);else if(last.q<.1)status('random-status','Signal is fading',`Only ${(last.q*100).toPrecision(3)}% of the input second moment remains.`,true);else status('random-status','Signal stays on scale','Compare several depths before deciding whether this scale is suitable.');chart('chart-random',[{name:activation==='tanh'?'tanh':'Linear',rows:result.rows,color:colors.teal}],'Signal second moment by layer');scenes.random.data={scale:width*sigma*sigma,rows:result.rows,depth,activation,wv:result.wv};scenes.random.draw();}
function updateXavier(){const width=number('xavier-width'),out=number('xavier-out'),depth=number('xavier-depth'),activation=$('xavier-activation').value,result=M.propagate({init:'xavier',activation,nIn:width,nOut:width,depth}),last=result.rows.at(-1);$('xavier-depth-value').textContent=depth+' layers';$('xavier-metrics').innerHTML=metric('Weight σ',fmt(Math.sqrt(result.wv)))+metric('Final q',fmt(last.q));status('xavier-status',activation==='linear'?'Expected signal preserved':'tanh changes the picture',activation==='linear'?'Equal widths give n × Var(w) = 1, so q stays at its input value.':'tanh compresses values. Gain-1 Xavier does not exactly preserve q in a deep nonlinear network.',activation==='tanh');$('xavier-calculator').innerHTML=`n<sub>in</sub> = ${width}, n<sub>out</sub> = ${out}<br>σ = √(2/${width+out}) = <strong>${Math.sqrt(2/(width+out)).toFixed(4)}</strong><br>Uniform bounds: ±${Math.sqrt(6/(width+out)).toFixed(4)}`;chart('chart-xavier',[{name:'Xavier · '+activation,rows:result.rows,color:colors.teal}],'Xavier forward signal by layer');scenes.xavier.data={rows:result.rows,activation,depth,wv:result.wv};scenes.xavier.draw();}
function updateHe(){const activation=$('he-activation').value,depth=number('he-depth'),init=$('he-init').value;const he=M.propagate({init:'he',activation,depth,nIn:128,nOut:128}),xavier=M.propagate({init:'xavier',activation,depth,nIn:128,nOut:128});const selected=init==='he'?he:xavier,last=selected.rows.at(-1);$('he-depth-value').textContent=depth+' layers';$('he-metrics').innerHTML=metric('He · final q',fmt(he.rows.at(-1).q))+metric('Xavier · final q',fmt(xavier.rows.at(-1).q));status('he-status',init==='he'?'Second moment preserved':'Second moment decays',init==='he'?'The weight scale compensates for the rectifier’s lost squared signal.':'Gain-1 Xavier does not compensate for the rectifier. Compare the two curves.',init!=='he');$('he-variance').innerHTML=`Selected ${init==='he'?'He':'Xavier'}:<br>E[a²] = <strong>${fmt(last.q)}</strong><br>Var(a) = <strong>${fmt(last.variance)}</strong>`;chart('chart-he',[{name:'He',rows:he.rows,color:colors.teal},{name:'Xavier',rows:xavier.rows,color:colors.orange}],'He versus Xavier in a rectifier network');scenes.he.data={init,depth,activation,rows:selected.rows,he:he.rows,xavier:xavier.rows,wv:selected.wv};scenes.he.draw();}
for(const id of ['sym-init','sym-depth','sym-break'])$(id).addEventListener('input',updateSymmetry);for(const id of ['random-sigma','random-activation','random-width','random-depth'])$(id).addEventListener('input',updateRandom);for(const id of ['xavier-width','xavier-out','xavier-activation','xavier-depth'])$(id).addEventListener('input',updateXavier);for(const id of ['he-activation','he-init','he-depth'])$(id).addEventListener('input',updateHe);
$('random-standard').addEventListener('click',()=>{$('random-sigma').value=0;updateRandom();});$('random-balanced').addEventListener('click',()=>{$('random-width').value=64;$('random-sigma').step='any';$('random-sigma').value=Math.log10(.125);updateRandom();});
updateSymmetry();updateRandom();updateXavier();updateHe();

// Guided playback links the spatial analogy to actual layer calculations.
const sceneGuides={
 symmetry:{title:'Read the paths',legend:'Each sphere represents a hidden unit. A shared coral path means identical features; different colors show distinct starting weights.',steps:['Initialize: all five units start with equal weights and zero biases.','Propagate: equal rows produce equal outputs. With symmetric downstream connections, their gradients also match.','Compare: enable the perturbation. Distinct weights permit distinct features, although poor scale can still saturate or erase signals.']},
 random:{title:'Separate the metaphor from the measurement',legend:'The amber particles and uneven terrain illustrate sensitivity to scale. Their positions are not measured activations. Follow the layer readout and chart to quantify growth or decay.',steps:['Start with input energy q₀ = E[x²] = 1. The weight scale is σ, so its variance is σ².','Multiply: each layer combines n inputs. Before activation, its variance is n × σ² × the incoming second moment.','Apply the activation: linear passes values through; tanh compresses large values toward −1 or +1. Repeat this operation through depth.']},
 xavier:{title:'Read the distribution ridges',legend:'Left to right is activation value. Front to back lists sampled layers, labeled L0, L1, … . Each ridge is scaled to the same peak height: compare horizontal spread, not ridge height. The orange highlight moves through the displayed layers.',steps:['Input: the first ridge shows centered unit-variance inputs. Most values lie close to zero.','Linear + Xavier: equal widths give n × Var(w) = 1. The ridges retain their spread in this expectation model.','Switch to tanh: the nonlinear compression narrows the distributions as depth increases. Watch q decrease in the layer readout.']},
 he:{title:'Compare balance and signal loss',legend:'Teal particles retain their illustrative size with He. Coral particles shrink with Xavier. The bowl and inward motion are an analogy for balanced starts, not a training trajectory. The two chart curves and readouts measure signal energy.',steps:['Mix: He weights give preactivation variance 2q for ReLU at equal widths. Xavier gives q.','Gate: ReLU keeps the positive half. Its output second moment is half the preactivation second moment.','Repeat: He gives 2 × ½ = 1 per layer. Xavier gives 1 × ½ = ½, so the signal fades with depth.']}
};
function setPlayback(scene,playing){scene.playing=playing;const b=document.querySelector(`[data-motion="${scene.type}"]`);b.textContent=playing?'Pause':'Play';b.setAttribute('aria-pressed',String(playing));}
for(const [key,scene] of Object.entries(scenes)){
 const guide=sceneGuides[key],panel=document.createElement('div');panel.className='visual-guide';panel.id=`guide-${key}`;
 panel.innerHTML=`<h4>${guide.title}</h4><p class="scene-legend">${guide.legend}</p><ol class="guide-steps">${guide.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="walk-controls"><label for="walk-${key}">Follow the layers <output id="walk-label-${key}"></output></label><input id="walk-${key}" type="range" min="0" max="100" step="0.1" value="0"><div class="walk-buttons"><button id="back-${key}" aria-label="Previous layer in ${key} experiment">← Previous layer</button><button id="next-${key}" aria-label="Next layer in ${key} experiment">Next layer →</button><label for="speed-${key}">Speed</label><select id="speed-${key}"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></div></div><div class="layer-flow" id="flow-${key}" aria-hidden="true"></div><div class="walk-readout" id="readout-${key}"></div><p class="walk-note">Pause to inspect a layer, drag the timeline, or use the layer buttons. A full pass takes 12 seconds at 1×. This animates a forward pass, not training iterations.</p>`;
 scene.canvas.closest('.visual-pane').querySelector('.visual-note').after(panel);
 scene.canvas.setAttribute('aria-describedby',panel.id);
 $(`walk-${key}`).addEventListener('input',()=>{setPlayback(scene,false);scene.phase=number(`walk-${key}`)/100;scene.draw();updateWalkthrough(scene,true);});
 for(const [direction,delta] of [['back',-1],['next',1]])$(`${direction}-${key}`).addEventListener('click',()=>{setPlayback(scene,false);const depth=scene.data.depth,layer=Math.floor(Math.min(1,scene.phase)*depth+1e-7);scene.phase=Math.max(0,Math.min(depth,layer+delta))/depth;scene.draw();updateWalkthrough(scene,true);});
 $(`speed-${key}`).addEventListener('change',()=>scene.speed=number(`speed-${key}`));
 document.querySelector(`[data-replay="${key}"]`).addEventListener('click',()=>{scene.phase=0;setPlayback(scene,true);updateWalkthrough(scene,true);});
 scene.canvas.closest('.experiment').querySelectorAll('.controls input,.controls select,.controls button').forEach(control=>control.addEventListener('input',()=>{scene.phase=0;scene.walkLayer=-1;scene.draw();updateWalkthrough(scene,true);}));
 updateWalkthrough(scene,true);
}
// Preset buttons emit clicks rather than input events.
for(const id of ['random-standard','random-balanced'])$(id).addEventListener('click',()=>{scenes.random.phase=0;scenes.random.draw();updateWalkthrough(scenes.random,true);});
function updateWalkthrough(scene,force=false){
 const key=scene.type,panel=$(`guide-${key}`);if(!panel)return;
 const depth=scene.data.depth||1,progress=Math.min(1,scene.phase),layer=Math.min(depth,Math.floor(progress*depth+1e-7));
 $(`walk-${key}`).value=progress*100;$(`walk-label-${key}`).textContent=layer===0?'Input':`Layer ${layer} / ${depth}`;
 if(scene.walkLayer===layer&&!force)return;scene.walkLayer=layer;
 $(`back-${key}`).disabled=layer===0;$(`next-${key}`).disabled=layer===depth;
 const stage=layer===0?0:layer===depth?2:1;panel.querySelectorAll('.guide-steps li').forEach((li,i)=>li.classList.toggle('current',i===stage));
 const checkpoints=[...new Set([0,Math.round(depth*.25),Math.round(depth*.5),Math.round(depth*.75),depth])];
 $(`flow-${key}`).innerHTML=checkpoints.map(n=>`<span class="${n<=layer?'visited':''} ${n===layer?'current':''}">${n===0?'Input':'L'+n}</span>`).join('<i>→</i>');
 let html='';
 if(key==='symmetry'){
  const row=layer===0?null:scene.data.rows[layer-1];
  html=layer===0?'<b>Input → first hidden layer</b><p>The input is [1, 2]. The five spheres stand for five hidden units, not five input values.</p>':`<b>Layer ${layer}: compare the five outputs</b><div class="unit-values">${row.map((v,i)=>`<span>N${i+1}<strong>${fmt(v)}</strong></span>`).join('')}</div><p>${scene.data.perturb?'Different weight rows permit different outputs. Tiny differences may disappear at the displayed precision, especially when tanh saturates.':'All five outputs match because the weight rows and biases match. The repeated feature carries no extra diversity.'}</p>`;
 }else{
  const row=scene.data.rows[layer],previous=scene.data.rows[Math.max(0,layer-1)];
  if(layer===0)html='<b>Input signal: q₀ = 1</b><p>Begin with centered inputs and unit second moment. Follow one layer to see the weight mixing and activation separately.</p>';
  else{
   const retain=previous.q?row.q/previous.q:0;
   html=`<b>Layer ${layer}: follow the calculation</b><div class="signal-calculation"><span>Incoming q<strong>${fmt(previous.q)}</strong></span><i>→</i><span>Before activation · E[z²]<strong>${fmt(row.preVariance)}</strong></span><i>→</i><span>After activation · q<strong>${fmt(row.q)}</strong></span></div><p>${key==='he'?`${scene.data.activation==='relu'?'ReLU retains ½':'Leaky ReLU retains 0.505'} of the preactivation second moment. `:scene.data.activation==='tanh'?'tanh compresses large inputs; output q never exceeds 1. ':'A linear activation leaves the second moment unchanged. '}This layer retains <strong>${fmt(retain)}×</strong> its incoming q.</p>`;
   if(scene.data.activation==='tanh')html+=`<p>Saturated outputs (|a| &gt; 0.95): <strong>${(row.saturation*100).toFixed(1)}%</strong>. Var(a) = ${fmt(row.variance)}.</p>`;
  }
  if(key==='he')html+=`<div class="comparison-readout"><span>He · q at L${layer}<strong>${fmt(scene.data.he[layer].q)}</strong></span><span>Xavier · q at L${layer}<strong>${fmt(scene.data.xavier[layer].q)}</strong></span></div>`;
  const svg=$(`chart-${key}`).querySelector('svg');let cursor=svg.querySelector('.layer-cursor');if(!cursor){cursor=document.createElementNS('http://www.w3.org/2000/svg','line');cursor.setAttribute('class','layer-cursor');cursor.setAttribute('y1','17');cursor.setAttribute('y2','153');cursor.setAttribute('stroke','#a26320');cursor.setAttribute('stroke-dasharray','3 3');svg.append(cursor);}cursor.setAttribute('x1',55+layer/depth*449);cursor.setAttribute('x2',55+layer/depth*449);
 }
 $(`readout-${key}`).innerHTML=html;
}
