/* =========================================================================
   GLOSSARY
   ========================================================================= */
var GLOSS = {
  regularisation:{
    term:"regularisation",
    def:"Any extra preference that stops a model from using its full capacity on the training sample. Penalties on weights, dropout, batch normalisation's noise, data augmentation, and early stopping are all regularisers. They usually raise bias a little to cut variance a lot.",
    formula:"Ẽ(θ) = E(θ) + λ Ω(θ)",
    see:"Goodfellow et al., Deep Learning (2016), ch. 7; Bishop & Bishop (2023), ch. 9; Prince, UDL, ch. 9."
  },
  parameter_norm:{
    term:"parameter-norm penalty",
    def:"Add λ times a norm of the weights to the training loss. The optimiser then trades fit against size. Which norm you pick (L1 or L2) changes the geometry of that trade, and therefore which weights survive.",
    formula:"Ω(w) = ‖w‖_q^q",
    see:"Goodfellow et al., §7.1; Bishop, PRML, §3.1.4."
  },
  l2:{
    term:"L2",
    def:"The squared Euclidean penalty Σ_i w_i². Contours are circles. The solution shrinks every weight toward zero but almost never hits exactly zero. Also called ridge when used with least squares, and (almost) weight decay in SGD.",
    formula:"Ω₂(w) = (1/2) ‖w‖₂²",
    see:"Goodfellow et al., §7.1.1; Bishop, PRML, §3.1.4; Bishop & Bishop §9.2."
  },
  l1:{
    term:"L1",
    def:"The absolute-value penalty Σ_i |w_i|. Contours are diamonds with corners on the axes. The solution is sparse: some weights become exactly zero. Also called the lasso in statistics.",
    formula:"Ω₁(w) = ‖w‖₁",
    see:"Goodfellow et al., §7.1.2; Bishop, PRML, §3.1.4 (q = 1); Bishop & Bishop fig. 9.6."
  },
  ridge:{
    term:"ridge",
    def:"Least squares plus an L2 penalty. Closed form: ŵ = (XᵀX + λI)⁻¹ Xᵀy. Large λ recovers a smaller effective parameter count. λ = 0 is ordinary least squares.",
    formula:"ŵ_λ = (XᵀX + λ I)⁻¹ Xᵀ y",
    see:"Bishop, PRML, §3.1.4; Bishop & Bishop, §4.1.6."
  },
  lasso:{
    term:"lasso",
    def:"Least squares plus an L1 penalty. No tidy closed form in general; coordinate descent or proximal gradient. The name is 'least absolute shrinkage and selection operator': it both shrinks and selects.",
    formula:"min_w ‖y − Xw‖² + λ ‖w‖₁",
    see:"Bishop, PRML, §3.1.4; Goodfellow et al., §7.1.2."
  },
  weight_decay:{
    term:"weight decay",
    def:"In SGD, the update w ← (1 − ηλ) w − η ∇E. For vanilla SGD this is equivalent to L2 on the loss. In adaptive methods (Adam) the two are not the same; decoupled weight decay (AdamW) restores the L2-like behaviour.",
    formula:"w ← (1 − ηλ) w − η ∇E",
    see:"Goodfellow et al., §7.1; Bishop & Bishop, §9.2; Loshchilov & Hutter, AdamW (2019)."
  },
  shrinkage:{
    term:"shrinkage",
    def:"Pulling coefficients toward zero. Ridge shrinks smoothly. Lasso shrinks and then clips at zero. Shrinkage cuts variance; if the true weights were large, it adds bias.",
    see:"Bishop, PRML, §3.2 (bias–variance) and §3.1.4."
  },
  sparsity:{
    term:"sparsity",
    def:"Many weights exactly zero, so the predictor uses only a subset of features (or hidden units). L1 produces this; L2 does not. Dropout produces sparsity in activations, not in the stored weights.",
    formula:"#{ i : w_i = 0 } large",
    see:"Goodfellow et al., §7.1.2; Bishop & Bishop, fig. 9.6."
  },
  soft_threshold:{
    term:"soft-thresholding",
    def:"The proximal map of λ|w|. Subtract λ from the absolute value and clip at zero, keeping the sign. This is the exact 1-D lasso update, and the reason small coefficients vanish.",
    formula:"S_λ(z) = sign(z) max(|z| − λ, 0)",
    see:"Goodfellow et al., §7.1.2 (subgradient of L1)."
  },
  dropout:{
    term:"dropout",
    def:"During training, independently set hidden units to zero with probability 1−p. Each minibatch trains a different thin subnetwork. At test time, use the full net with weights (or activations) scaled so the expected input matches training.",
    formula:"h̃ = (m ⊙ h) / p    with m_i ~ Bernoulli(p)",
    see:"Srivastava et al. (2014); Goodfellow et al., §7.12; Prince, UDL, figs. 9.8–9.9; Bishop & Bishop, §9.6.1."
  },
  inverted_dropout:{
    term:"inverted dropout",
    def:"The modern implementation: divide by p at train time, leave the graph untouched at test time. Equivalent to multiplying leftover weights by p at test (the original paper), but cheaper and less error-prone.",
    formula:"train: h̃ = m ⊙ h / p ;  test: h̃ = h",
    see:"Goodfellow et al., §7.12; Srivastava et al. (2014)."
  },
  keep_probability:{
    term:"keep probability",
    def:"p, the chance a unit is kept. Typical values: 0.8–0.9 for input, 0.5–0.8 for hidden. p = 1 is 'no dropout'. Smaller p is stronger regularisation and a noisier gradient.",
    formula:"P(m_i = 1) = p",
    see:"Srivastava et al. (2014); Prince, UDL, §9.3."
  },
  batch_norm:{
    term:"batch normalisation",
    def:"For each channel, subtract the minibatch mean and divide by the minibatch standard deviation, then apply a learned scale γ and shift β. At test time, replace batch statistics by a running average collected during training.",
    formula:"û = (u − μ_B) / √(σ_B² + ε),   y = γ û + β",
    see:"Ioffe & Szegedy (2015); Bishop & Bishop, §7.4.2; Prince, UDL, §11.4; Goodfellow et al., §8.7.1."
  },
  scale_shift:{
    term:"scale-and-shift",
    def:"The affine pair (γ, β) after normalisation. Without them, the layer would be forced to zero mean and unit variance, which can destroy a useful representation (a sigmoid wants to sit off zero). They let the net undo the normalisation if it should.",
    formula:"y = γ û + β",
    see:"Ioffe & Szegedy (2015); Prince, UDL, §11.4."
  },
  running_stats:{
    term:"running statistics",
    def:"Exponential moving averages of μ_B and σ_B², updated every training step. Used at test time so a single example (or a tiny batch) still has a defined normalisation. If you forget to switch, test predictions depend on whoever else is in the batch.",
    formula:"μ ← α μ + (1−α) μ_B",
    see:"Ioffe & Szegedy (2015); Bishop & Bishop, §7.4.2."
  },
  internal_covariate:{
    term:"internal covariate shift",
    def:"Ioffe & Szegedy's original motivation: the distribution of each layer's inputs keeps moving as earlier layers train, so later layers chase a moving target. Later work (Santurkar et al. 2018) argues BN helps more by smoothing the loss landscape. Both stories are still taught; the algebra of BN does not depend on which you prefer.",
    see:"Ioffe & Szegedy (2015); Santurkar et al. (2018); Prince, UDL, §11.4."
  },
  early_stopping:{
    term:"early stopping",
    def:"Monitor validation loss (or error) while you train. Save the parameters at the best validation point and stop when it has not improved for a patience window. Acts like a regulariser: the optimiser has not had time to fit every noise wiggle.",
    formula:"θ̂ = θ_{t*}  with t* = arg min_t L_val(θ_t)",
    see:"Goodfellow et al., §7.8; Bishop, PRML, §5.5.2; Prince, UDL, fig. 9.6; Bishop & Bishop, §9.3.1."
  },
  validation_set:{
    term:"validation set",
    def:"A split used to choose hyperparameters (λ, p, patience, architecture) but not to update θ by gradient descent. Once you have used a split to make choices, it is no longer an honest test.",
    see:"Goodfellow et al., §5.3."
  },
  hyperparameters:{
    term:"hyperparameters",
    def:"Choices the inner optimiser does not fit: λ, dropout p, BN momentum, patience, learning rate. Tune them on validation data, then report test loss once.",
    see:"Goodfellow et al., §5.3."
  },
  effective_parameters:{
    term:"effective parameters",
    def:"How many degrees of freedom the fit actually uses after regularisation. Ridge with large λ can make a 100-weight model behave like a 3-weight one. Early stopping has an analogous 'effective number of iterations'.",
    see:"Bishop, PRML, §3.5.3 and §5.5.2 (effective number of parameters)."
  },
  overfitting:{
    term:"overfitting",
    def:"Training loss looks excellent; test loss does not. The model used capacity to fit sample noise. Regularisers exist to stop that.",
    formula:"large generalisation gap",
    see:"Goodfellow et al., §5.2."
  },
  underfitting:{
    term:"underfitting",
    def:"Training loss stays high. The class is too small, λ is too large, dropout p is too small, or you stopped far too early.",
    see:"Goodfellow et al., §5.2."
  },
  generalisation:{
    term:"generalisation",
    def:"Performance on new draws from the same process. Training loss is only a proxy. Every method on this sheet is a way of buying better generalisation, usually at some cost to training fit.",
    see:"Prince, UDL, ch. 9; Goodfellow et al., ch. 7."
  },
  generalisation_gap:{
    term:"generalisation gap",
    def:"L_test − L_train. Regularisation typically raises L_train a little and lowers L_test, shrinking the gap.",
    formula:"gap = L_test − L_train",
    see:"Goodfellow et al., §5.2."
  },
  training_loss:{
    term:"training loss",
    def:"Average loss on the examples the optimiser sees. With a penalty, the number you minimise is training loss plus Ω, not training loss alone.",
    see:"Bishop & Bishop, ch. 4."
  },
  test_loss:{
    term:"test loss",
    def:"Loss on a held-out sample unused for θ and unused for hyperparameters. The number you publish.",
    see:"Goodfellow et al., §5.3."
  },
  bias:{
    term:"bias",
    def:"How far the average predictor sits from the true function. Regularisation usually increases bias (the average fit is pulled toward a simpler function).",
    formula:"Bias(x) = E_D[f̂_D(x)] − f(x)",
    see:"Bishop, PRML, §3.2."
  },
  variance:{
    term:"variance",
    def:"How much the fitted function jumps when you redraw the training set. Regularisation usually cuts variance. That is the point.",
    formula:"Var(x) = E_D[(f̂_D(x) − E_D[f̂_D])²]",
    see:"Bishop, PRML, §3.2."
  },
  capacity:{
    term:"capacity",
    def:"How large a family of functions the model can represent. Regularisation reduces effective capacity without changing the architecture.",
    see:"Goodfellow et al., §5.2."
  },
  least_squares:{
    term:"least squares",
    def:"Minimise mean squared error on the training set. Unregularised, for a linear-in-parameters model, this is a linear system.",
    formula:"θ̂ = arg min_θ ‖y − Φθ‖²",
    see:"Bishop, PRML, §3.1."
  },
  inductive_bias:{
    term:"inductive bias",
    def:"The assumptions a learner makes in order to generalise at all. Convolution assumes locality; residual skips assume the identity is a good default. Regularisers are extra inductive biases stacked on the architecture.",
    see:"Bishop & Bishop (2023), §9.1; Goodfellow et al., §5.2."
  },
  mse:{
    term:"mean squared error",
    def:"Average of squared residuals. All hand calculations on this sheet use MSE or SSE = N · MSE, and round to 4 decimals at every step.",
    formula:"MSE = (1/N) Σᵢ (yᵢ − ŷᵢ)²",
    see:"Bishop, PRML, §1.1."
  }
};

var BLANKS = [
{id:"P1", sec:1, wide:true,
 prompt:"Regularisation is designed to improve {{slot}}.",
 need:["the point of the previous worksheet"],
 correct:"test performance, possibly at the cost of training fit",
 options:["test performance, possibly at the cost of training fit",
          "training loss until it is exactly zero",
          "the number of layers, which always helps"],
 hints:{"training loss until it is exactly zero":"Interpolation is often the problem, not the goal. Goodfellow ch. 7 opens with the opposite: we accept worse training error to get better test error.",
        "the number of layers, which always helps":"Depth is capacity. Regularisation is a preference inside a class that may already be large."}},
{id:"P2", sec:1, wide:true,
 prompt:"The number you actually minimise with a penalty is {{slot}}.",
 need:["Ẽ = E + λ Ω"],
 correct:"training loss plus λ times a regulariser",
 options:["training loss plus λ times a regulariser",
          "test loss, directly",
          "validation loss, by gradient descent on that split"],
 hints:{"test loss, directly":"You do not have ∇ of the test loss. That is the whole point of a proxy.",
        "validation loss, by gradient descent on that split":"Validation is for choosing λ, not for the inner optimiser. Using it as a training set destroys the split."}},
{id:"L2a", sec:2,
 prompt:"SSE = (2 − w)² + (3 − 2w)² expands to 5w² − 16w + 13. Unregularised, d(SSE)/dw = 10w − 16 = 0 so w = {{slot}}.",
 need:["table A: (x,y) = (1,2) and (2,3)","ŷ = w x"],
 correct:"1.6",
 options:["1.6","0.8","2","1.3333"],
 hints:{"0.8":"You halved 16/10 twice, or took 8/10. 16/10 = 1.6.",
        "2":"That would fit the first point only (w = y/x = 2/1).",
        "1.3333":"That is the ridge solution at λ = 1, two steps from now."}},
{id:"L2b", sec:2,
 prompt:"ŷ(1) = 1.6 · 1 = 1.6 and ŷ(2) = 1.6 · 2 = {{slot}}.",
 need:["w = 1.6"],
 correct:"3.2",
 options:["3.2","3.0","1.6","4.8"],
 hints:{"3.0":"That is the second y, not the prediction.",
        "1.6":"That is ŷ(1).",
        "4.8":"You did 1.6 × 3."}},
{id:"L2c", sec:2,
 prompt:"SSE = (2 − 1.6)² + (3 − 3.2)² = 0.16 + 0.04 = {{slot}}.",
 need:["ŷ = 1.6 and 3.2"],
 correct:"0.2",
 options:["0.2","0.1","0.4","0"],
 hints:{"0.1":"That is MSE = SSE / 2. The expansion used SSE.",
        "0.4":"You added the residuals, not the squares.",
        "0":"The line ŷ = w x cannot hit both points."}},
{id:"L2d", sec:2,
 prompt:"Add λ w² to SSE. Stationarity: 10w − 16 + 2λ w = 0, so w = 8 / (5 + λ). At λ = 1, w = {{slot}}.",
 need:["the unregularised critical point was w = 1.6"],
 correct:"1.3333",
 options:["1.3333","1.6","0.8","2"],
 hints:{"1.6":"That is λ = 0. Plug λ = 1 into 8/(5+λ).",
        "0.8":"8/10, as if λ = 5.",
        "2":"You inverted the formula."}},
{id:"L2e", sec:2, wide:true,
 prompt:"Compared with λ = 0, the λ = 1 fit has {{slot}}.",
 need:["w dropped from 1.6 to 1.3333","SSE rose from 0.2000 to 0.5556"],
 correct:"smaller |w|, higher training SSE",
 options:["smaller |w|, higher training SSE",
          "larger |w|, lower training SSE",
          "the same w, because least squares ignores λ"],
 hints:{"larger |w|, lower training SSE":"Ridge shrinks. Training SSE is allowed to get worse; that is the trade.",
        "the same w, because least squares ignores λ":"The stationarity condition changed: +2λw."}},
{id:"L2f", sec:2, wide:true,
 prompt:"In the (w₁, w₂) plane, L2 contours are {{slot}}.",
 need:["Goodfellow fig. 7.1 / Bishop fig. 9.6"],
 correct:"circles (or ellipses after a change of variables)",
 options:["circles (or ellipses after a change of variables)",
          "diamonds with corners on the axes",
          "straight lines through the origin"],
 hints:{"diamonds with corners on the axes":"That is L1. Circles have no corners, which is why L2 almost never hits an axis.",
        "straight lines through the origin":"Those would be a linear penalty in one direction, not ‖w‖₂²."}},
{id:"L1a", sec:3,
 prompt:"The 1-D proximal map S_λ(z) = sign(z) max(|z| − λ, 0) applied to z = 2.5, λ = 1 is {{slot}}.",
 need:["soft-thresholding"],
 correct:"1.5",
 options:["1.5","2.5","0","3.5"],
 hints:{"2.5":"You forgot to subtract λ.",
        "0":"|z| = 2.5 > 1, so it does not clip.",
        "3.5":"You added λ. Soft-thresholding shrinks toward zero."}},
{id:"L1b", sec:3,
 prompt:"S_1(0.4) = {{slot}}.",
 need:["|z| = 0.4 < λ = 1"],
 correct:"0",
 options:["0","−0.6","0.4","1"],
 hints:{"−0.6":"You subtracted and kept a leftover with the wrong sign. When |z| < λ the result is exactly 0.",
        "0.4":"The whole point of the clip: small values die.",
        "1":"That is λ, not the output."}},
{id:"L1c", sec:3,
 prompt:"S_1(−1.7) = {{slot}}.",
 need:["keep the sign, subtract 1 from 1.7"],
 correct:"−0.7",
 options:["−0.7","0.7","−1.7","0"],
 hints:{"0.7":"The sign of z is negative.",
        "−1.7":"You skipped the shrinkage.",
        "0":"|z| = 1.7 > 1, so it survives, smaller."}},
{id:"L1d", sec:3,
 prompt:"Unregularised least squares on table B gives w ≈ (1.9483, 0.1759). Lasso with λ = 2 (SSE + λ‖w‖₁) gives w ≈ (1.8933, {{slot}}).",
 need:["table B","L1 sets small weights to zero"],
 correct:"0",
 options:["0","0.1759","1.8933","−0.1759"],
 hints:{"0.1759":"That is the OLS second weight. L1 has already killed it at this λ.",
        "1.8933":"That is w₁, not w₂.",
        "−0.1759":"Sign flip is not what lasso does here."}},
{id:"L1e", sec:3, wide:true,
 prompt:"L1 diamonds have corners on the axes, so the loss contour often first touches {{slot}}.",
 need:["Bishop & Bishop fig. 9.6 / PRML fig. 3.4"],
 correct:"a corner, where at least one weight is exactly zero",
 options:["a corner, where at least one weight is exactly zero",
          "a smooth point where both weights stay nonzero",
          "the unregularised OLS solution, always"],
 hints:{"a smooth point where both weights stay nonzero":"That is the typical L2 (circle) contact.",
        "the unregularised OLS solution, always":"OLS is the centre of the ellipses, outside a small constraint region."}},
{id:"D1a", sec:4,
 prompt:"Inverted dropout, p = 0.5, h = 1.2, m = 1. The forwarded value is m h / p = {{slot}}.",
 need:["table D","divide by p at train time"],
 correct:"2.4",
 options:["2.4","1.2","0.6","0"],
 hints:{"1.2":"You skipped the 1/p scale. Inverted dropout inflates kept units.",
        "0.6":"You multiplied by p instead of dividing.",
        "0":"m is 1, so the unit is kept."}},
{id:"D1b", sec:4,
 prompt:"Same layer, h = −0.4, m = 0. Forwarded value {{slot}}.",
 need:["dropped units contribute nothing"],
 correct:"0",
 options:["0","−0.8","−0.4","0.4"],
 hints:{"−0.8":"m = 0 zeros the unit before any scale.",
        "−0.4":"Still nonzero. The mask is 0.",
        "0.4":"Sign and mask both wrong."}},
{id:"D2", sec:4, wide:true,
 prompt:"At test time with inverted dropout you {{slot}}.",
 need:["the 1/p was already applied in training"],
 correct:"run the full network with no mask and no extra scale",
 options:["run the full network with no mask and no extra scale",
          "keep dropping units, otherwise the net is unregularised at test",
          "multiply every weight by p, because training never scaled"],
 hints:{"keep dropping units, otherwise the net is unregularised at test":"Dropout is a training regulariser. Test predictions should be deterministic. The ensemble is approximated by the full net.",
        "multiply every weight by p, because training never scaled":"That is the original (non-inverted) convention. Inverted dropout already divided by p on the way up."}},
{id:"D3", sec:4, wide:true,
 prompt:"Dropout's usual story is that it trains {{slot}}.",
 need:["Goodfellow fig. 7.6"],
 correct:"an ensemble of subnetworks that share weights",
 options:["an ensemble of subnetworks that share weights",
          "a single thinner architecture that is then frozen",
          "an L2 penalty exactly equal to p(1−p)‖w‖²"],
 hints:{"a single thinner architecture that is then frozen":"Which units drop changes every step. The stored architecture stays wide.",
        "an L2 penalty exactly equal to p(1−p)‖w‖²":"There is a loose noise/L2 link for linear models, but dropout is not identical to ridge."}},
{id:"B1", sec:5,
 prompt:"Batch mean of {1, 3, 5, 7} is {{slot}}.",
 need:["table C"],
 correct:"4",
 options:["4","5","3.5","16"],
 hints:{"5":"That is one of the values, or (3+7)/2.",
        "3.5":"(1+7)/2, skipping the middle.",
        "16":"You summed and forgot to divide by 4."}},
{id:"B2", sec:5,
 prompt:"Population batch variance (1/N) Σ (u − μ)² = (9 + 1 + 1 + 9) / 4 = {{slot}}.",
 need:["μ = 4","deviations −3, −1, +1, +3"],
 correct:"5",
 options:["5","6.6667","4","2.2361"],
 hints:{"6.6667":"That is the unbiased / (N−1) version. Ioffe & Szegedy use / N in the forward pass (plus ε).",
        "4":"That is μ again.",
        "2.2361":"That is √5, the standard deviation."}},
{id:"B3", sec:5,
 prompt:"û for the first example: (1 − 4) / √5 = {{slot}}.",
 need:["μ = 4","σ² = 5"],
 correct:"−1.3416",
 options:["−1.3416","−3","1.3416","−0.8"],
 hints:{"−3":"You forgot to divide by √5.",
        "1.3416":"Sign: 1 − 4 is negative.",
        "−0.8":"You divided by 5, not √5."}},
{id:"B4", sec:5,
 prompt:"After scale-and-shift with γ = 2, β = 1: y₁ = 2(−1.3416) + 1 = {{slot}}.",
 need:["û₁ = −1.3416"],
 correct:"−1.6832",
 options:["−1.6832","−1.3416","2.6832","1"],
 hints:{"−1.3416":"That is û, before γ, β.",
        "2.6832":"Sign error on 2 × (−1.3416).",
        "1":"That is β alone."}},
{id:"B5", sec:5, wide:true,
 prompt:"At test time, batch normalisation replaces μ_B, σ_B² by {{slot}}.",
 need:["a single test example has no meaningful batch"],
 correct:"running averages collected during training",
 options:["running averages collected during training",
          "the statistics of whatever other examples happen to share the batch",
          "μ = 0 and σ² = 1, always"],
 hints:{"the statistics of whatever other examples happen to share the batch":"That makes a prediction depend on its neighbours. That is a bug (train-mode BN at test).",
        "μ = 0 and σ² = 1, always":"Then γ, β would have to do all the work and a single example would still need a std. The running average is the standard fix."}},
{id:"E1", sec:6, wide:true,
 prompt:"You stop at the epoch where {{slot}}.",
 need:["the figure of training vs validation curves"],
 correct:"validation loss is best (with some patience)",
 options:["validation loss is best (with some patience)",
          "training loss first hits zero",
          "training and validation curves cross, always"],
 hints:{"training loss first hits zero":"That is often past the useful point: interpolation of the sample.",
        "training and validation curves cross, always":"They need not cross. You care about the validation minimum, not a crossing."}},
{id:"E2", sec:6, wide:true,
 prompt:"Early stopping is a regulariser because {{slot}}.",
 need:["Bishop §5.5.2 / Goodfellow §7.8"],
 correct:"the optimiser has not yet used its full capacity to fit noise",
 options:["the optimiser has not yet used its full capacity to fit noise",
          "it changes the architecture by deleting layers",
          "it is identical to setting λ = 0"],
 hints:{"it changes the architecture by deleting layers":"The graph is unchanged. Time is the constraint.",
        "it is identical to setting λ = 0":"λ = 0 is unregularised. Early stopping is closer to a large-λ / small-effective-time limit."}},
{id:"C1", sec:7, wide:true,
 prompt:"You want a sparse linear model for feature selection. First tool {{slot}}.",
 need:["L1 vs L2 geometry"],
 correct:"L1 / lasso",
 options:["L1 / lasso","L2 / ridge","dropout on the inputs, p = 0.99"],
 hints:{"L2 / ridge":"Ridge shrinks but keeps everyone nonzero.",
        "dropout on the inputs, p = 0.99":"Almost no dropout, and dropout does not store zeros in w."}},
{id:"C2", sec:7, wide:true,
 prompt:"A deep conv net trains slowly and activations explode in depth. The standard extra layer is {{slot}}.",
 need:["Prince §11.4, Ioffe & Szegedy"],
 correct:"batch normalisation (or a close variant)",
 options:["batch normalisation (or a close variant)",
          "lasso on the pixels",
          "early stopping before the first epoch ends"],
 hints:{"lasso on the pixels":"Sparsity on inputs is not what fixes internal scaling.",
        "early stopping before the first epoch ends":"That underfits. BN is about the forward/backward scales while you still train."}}
];

var SECTIONS = [
{n:1, eyebrow:"part 1", title:"Why add anything to the loss?",
 result:"regularisation trades training fit for test performance",
 blocks:[
  {t:"hook", q:"If training loss is already going down, why would we add a term that makes it worse?",
   hint:"The quantity we care about is not the quantity we can differentiate on the training set."},
  {t:"p", html:"The last worksheet ended here: {t:overfitting} is a large {t:generalisation_gap}. {t:capacity} lets the model interpolate the sample, including noise. {t:regularisation} is a name for any extra preference that stops that interpolation without you having to shrink the architecture by hand."},
  {t:"p", html:"Goodfellow, Bengio & Courville (ch. 7) put it as a definition: strategies that reduce test error, possibly at the expense of training error. Bishop & Bishop (ch. 9) start from the polynomial we already know — add (λ/2) wᵀw to the error — and then spend a chapter listing the modern versions of that idea. Prince (UDL ch. 9) splits the same ground into explicit penalties and implicit ones (the optimiser, the stopping time, the noise in SGD)."},
  {t:"card", v:"navy", html:
    "<div class=\"eyebrow\">the regularised objective</div>" +
    "<div class=\"mathline big\">Ẽ(w) = E(w) + {lam} Ω(w)</div>" +
    "<p class=\"txt\" style=\"margin:10px 0 0\">E is the data term (MSE, cross-entropy). Ω is a preference. {lam} ≥ 0 is a {t:hyperparameters} you do <em>not</em> fit by gradient descent on the training set. Tune it on a {t:validation_set}.</p>"},
  {t:"lines", items:[
    "{lam} = 0 recovers ordinary training. Every method below has a 'turn it off' setting.",
    "Large {lam} (or small dropout p, or a tiny stopping time) is a smaller effective model: {t:underfitting} if you overdo it.",
    "The five tools on this sheet attack the same gap from different directions: shrink weights (L2), delete weights (L1), delete activations (dropout), re-scale activations (batch norm), or stop the search (early stopping)."
  ]},
  {t:"raw", html: figHTML("figs/prml_fig17_lambda.png",
    "Bishop, Pattern Recognition and Machine Learning (2006), fig. 1.7 — polynomial fit as ln λ varies. Large λ underfits; small λ overfits. This is the whole subject in one picture.")},
  {t:"blank", id:"P1"},
  {t:"blank", id:"P2"},
  {t:"mcq", tag:"part 1 · question 1", answer:2,
   q:"You drive training loss to 0.0000 with a wide net. Test loss is high. Which statement is the most accurate next move?",
   opts:[
     {txt:"The architecture is wrong; only a smaller net can generalise.",
      hint:"Overparameterised nets often generalise. Regularisation, more data, or a different implicit bias can be enough."},
     {txt:"Test loss cannot be high if training loss is zero: you must have leaked the test set.",
      hint:"Interpolation of the training sample is compatible with terrible test error. That was overfitting."},
     {txt:"The model had enough capacity to interpolate the sample. Add a regulariser, more data, or change the implicit bias of training.", hint:""},
     {txt:"Increase λ until training loss is also high, so the two losses match.",
      hint:"Matching a high training loss to a high test loss is underfitting. You want the test number down, not the gap cosmetic."}],
   why:"{t:regularisation} is a knob on effective {t:capacity}. Matching a high train loss to a high test loss is not a win."},
  {t:"answer", html:"<p>Write Ẽ = E + {lam} Ω on the page and refuse to minimise E alone when the model can interpolate. Everything below is a choice of Ω, or a procedure that behaves like one.</p>"}
 ]},

{n:2, eyebrow:"part 2", title:"L2, ridge, and weight decay",
 result:"L2 shrinks every weight; closed form ŵ = (XᵀX + λI)⁻¹ Xᵀy",
 blocks:[
  {t:"hook", q:"What does adding λ‖w‖² actually do to a number you can compute by hand?",
   hint:"Two points, one weight, ŷ = w x."},
  {t:"p", html:"{t:l2} is the default {t:parameter_norm}. Bishop (PRML §3.1.4) writes the regularised least-squares error as"},
  {t:"math", big:true, html:"Ẽ(w) = (1/2) Σ_n (y_n − wᵀ φ_n)² + ({lam}/2) ‖w‖₂²"},
  {t:"p", html:"Set the gradient to zero and the data term XᵀX w − Xᵀy is joined by {lam} w. Rearrange:"},
  {t:"math", html:"ŵ = (XᵀX + {lam} I)⁻¹ Xᵀ y"},
  {t:"p", html:"That is {t:ridge}. Compared with ordinary {t:least_squares}, you have added {lam} to every eigenvalue of XᵀX. Directions the data do not constrain (tiny eigenvalues) are the ones {t:shrinkage} hits hardest. That is also why ridge is a numerical regulariser: XᵀX + {lam}I is invertible even when XᵀX is not."},
  {t:"h3", html:"A two-point calculation, fully expanded"},
  {t:"p", html:"Table A. Model ŷ = w x (no intercept), squared error summed not averaged, penalty {lam} w² added to that SSE. Every value rounded to 4 decimals after each step, so a calculator matches the chips."},
  {t:"raw", html: T_1D()},
  {t:"worked", tag:"unregularised", title:"λ = 0",
   lines:[
     "SSE(w) = (2 − w)² + (3 − 2w)² = 5w² − 16w + 13",
     "d(SSE)/dw = 10w − 16 = 0  ⇒  w = 1.6000",
     "ŷ = (1.6000, 3.2000),  SSE = 0.2000,  MSE = 0.1000"
   ],
   note:"The line cannot hit both points. Residual +0.4000 at x = 1 and −0.2000 at x = 2."},
  {t:"blank", id:"L2a"},
  {t:"blanks", ids:["L2b"], prompt:"ŷ(2) = 1.6 × 2 = {{L2b}}", need:["w = 1.6"]},
  {t:"blank", id:"L2c"},
  {t:"worked", tag:"ridge", title:"λ = 1, same two points",
   lines:[
     "Ẽ(w) = 5w² − 16w + 13 + λ w²",
     "dẼ/dw = 10w − 16 + 2λ w = 0  ⇒  w = 8 / (5 + λ)",
     "λ = 1 ⇒ w = 8/6 = 1.3333",
     "ŷ = (1.3333, 2.6667),  SSE = 0.5556,  λ w² = 1.7777,  Ẽ = 2.3333"
   ],
   note:"Training SSE got worse (0.2000 → 0.5556). |w| got smaller (1.6000 → 1.3333). That swap — a little bias, less variance — is the L2 move."},
  {t:"blank", id:"L2d"},
  {t:"blank", id:"L2e"},
  {t:"h3", html:"Geometry: why L2 almost never zeros a weight"},
  {t:"p", html:"In two dimensions the constraint ‖w‖₂² ≤ η is a disk. The unregularised loss has elliptical contours centred at the OLS solution. The regularised solution is where the smallest ellipse that still touches the disk meets the boundary. A circle has no corners on the axes, so that meeting point almost never has a coordinate equal to zero. Goodfellow's fig. 7.1 is the gradient-balance version of the same picture: ∇E points out of the ellipses, {lam} w points toward the origin, and they cancel at ŵ."},
  {t:"raw", html: figHTML("figs/gdl_fig71_l2.png",
    "Goodfellow, Bengio & Courville, Deep Learning (2016), fig. 7.1 — L2 as a balance between data-loss ellipses and circular penalty contours.")},
  {t:"raw", html: figHTML("figs/dlfc_fig96_l1l2.png",
    "Bishop & Bishop, Deep Learning: Foundations and Concepts (2023), fig. 9.6 — constraint regions. Right: L2 disk. Left: L1 diamond (used in the next part).")},
  {t:"blank", id:"L2f"},
  {t:"h3", html:"Weight decay is L2, until it isn't"},
  {t:"p", html:"Take a gradient step on E + ({lam}/2)‖w‖². The extra gradient is {lam} w, so"},
  {t:"math", html:"w ← w − η (∇E + {lam} w) = (1 − η{lam}) w − η ∇E"},
  {t:"p", html:"That multiplicative (1 − η{lam}) is {t:weight_decay}. For vanilla SGD it is the same as {t:l2} on the loss. For Adam, the two diverge: the adaptive denominator rescales ∇E but would also rescales the L2 gradient if you fold λ into the loss. Decoupled weight decay (AdamW) applies (1 − ηλ) after the adaptive step, which is what people usually want when they say 'L2'."},
  {t:"anim", id:"r1", title:"Visualiser 1 · ridge on a degree-9 polynomial",
   intro:"Six noisy samples of a sine (the same toy as the generalisation sheet). M = 9 would interpolate wildly at λ = 0. Drag λ. Watch training MSE rise and the wiggle die — then, if you go too far, the curve flatten into an underfit."},
  {t:"raw", html: figHTML("figs/udl_fig92_l2.png",
    "Prince, Understanding Deep Learning, fig. 9.2 — L2 on a small network: as the penalty grows, the fitted function loses kinks. Same knob as this visualiser.")},
  {t:"mcq", tag:"part 2 · question 2", answer:0,
   q:"XᵀX is singular (more features than points). Ordinary least squares has infinitely many interpolators. Ridge with λ > 0",
   opts:[
     {txt:"picks a unique solution: the one with smallest ‖w‖₂ among the near-interpolators, in the limit λ → 0⁺.", hint:""},
     {txt:"is also undefined, because you still have to invert XᵀX.",
      hint:"You invert XᵀX + λI, which is positive definite for λ > 0."},
     {txt:"sets every weight to zero for any λ > 0.",
      hint:"Only as λ → ∞. For small λ the data term still matters."},
     {txt:"becomes L1, which is the unique sparse interpolator.",
      hint:"Different penalty. The Moore–Penrose / min-norm interpolator is an L2 object."}],
   why:"Adding {lam}I is both numerically well-posed and a selection rule: among the directions that fit the data equally well, prefer small Euclidean length."},
  {t:"answer", html:"<p>Remember three facts. (1) ŵ = (XᵀX + {lam}I)⁻¹ Xᵀy. (2) Every coordinate shrinks; none typically hits zero. (3) Weight decay is this penalty, implemented as a multiplicative fade on w, equivalent for vanilla SGD.</p>"}
 ]},

{n:3, eyebrow:"part 3", title:"L1, lasso, and exact zeros",
 result:"L1 diamonds put the solution on an axis; soft-thresholding is the 1-D update",
 blocks:[
  {t:"hook", q:"Ridge never quite kills a useless feature. What penalty does?",
   hint:"Corners on the axes."},
  {t:"p", html:"Replace ‖w‖₂² by ‖w‖₁ = Σ |w_i|. Bishop writes a family Ω_q = Σ |w_j|^q and notes that q = 1 is special: it is still convex, but the constraint region has corners. That is {t:lasso}. Convex, so local minima are global; nondifferentiable at 0, so you work with subgradients or a proximal map."},
  {t:"h3", html:"Why the diamond zeros a coordinate"},
  {t:"p", html:"Constraint form: minimise E(w) subject to |w₁| + |w₂| ≤ η. The feasible set is a diamond whose vertices sit on the axes. Expanding loss ellipses, centred at OLS, typically first touch a vertex. At a vertex one coordinate is exactly zero. That is {t:sparsity}. The L2 disk, by contrast, is smooth, so the first contact is a generic angle and both weights survive."},
  {t:"raw", html: figHTML("figs/prml_fig34_qnorms.png",
    "Bishop, PRML (2006), fig. 3.4 — constraint regions for Σ |w_j|^q ≤ η. q = 2 is the disk; q = 1 is the diamond; q < 1 is even spikier (but non-convex).")},
  {t:"p", html:"Goodfellow §7.1.2 gives the calculus version. The subgradient of |w| at 0 is the whole interval [−1, 1]. The data gradient has to be larger than {lam} in absolute value before the weight will leave 0. Small signals never make it; they are {t:soft_threshold}ed away."},
  {t:"raw", html: figHTML("figs/gdl_l1.png",
    "Goodfellow et al. (2016), §7.1.2 — L1 regularisation. The penalty is linear in |w|, unlike the parabola of L2, which is why small weights feel a constant push toward zero.")},
  {t:"h3", html:"The one-dimensional map you should be able to draw"},
  {t:"math", big:true, html:"S_{lam}(z) = sign(z) max(|z| − {lam}, 0)"},
  {t:"p", html:"Three cases. |z| > {lam}: move z toward 0 by {lam}. |z| ≤ {lam}: output 0. This is the exact minimiser of (1/2)(w − z)² + {lam}|w|, and it is the lasso update when features are orthogonal. We will apply it by hand to three numbers."},
  {t:"blank", id:"L1a"},
  {t:"blank", id:"L1b"},
  {t:"blank", id:"L1c"},
  {t:"h3", html:"Five points, two features: OLS versus lasso"},
  {t:"p", html:"Table B. Feature 2 is almost a decoy (true relation ≈ 2 x₁). Unregularised {t:least_squares} still gives it a small nonzero weight, because that shaves a little training SSE. Lasso at λ = 2 (penalty added to SSE) sets w₂ exactly to 0 and only slightly shrinks w₁."},
  {t:"raw", html: T_2D()},
  {t:"worked", tag:"table B", title:"OLS versus lasso λ = 2",
   lines:[
     "XᵀX = [[15, 1], [1, 2]],   Xᵀy = [29.4, 2.3]",
     "OLS: w = (1.9483, 0.1759),   train MSE = 0.0032",
     "Lasso (SSE + λ‖w‖₁, λ = 2, coordinate descent): w = (1.8933, 0.0000)",
     "Lasso train MSE = 0.0285  (worse on train, one feature gone)"
   ],
   note:"Ridge at the same λ would have given (1.7209, 0.1448) — both coordinates smaller, neither zero. Check visualiser 3."},
  {t:"blank", id:"L1d"},
  {t:"blank", id:"L1e"},
  {t:"anim", id:"r2", title:"Visualiser 2 · diamond versus disk",
   intro:"Grey ellipses: contours of a quadratic loss centred at the OLS star. Amber: L1 diamond. Navy: L2 disk. Drag the budget η. The marker is where the contour first touches the constraint. Watch the L1 marker snap to an axis; the L2 marker slides and stays off-axis."},
  {t:"anim", id:"r3", title:"Visualiser 3 · regularisation paths on table B",
   intro:"Horizontal axis is λ (log). Vertical is each weight. Solid: lasso. Dashed: ridge. Lasso's w₂ hits exactly 0 and stays there; ridge's w₂ only approaches 0 as λ → ∞."},
  {t:"mcq", tag:"part 3 · question 3", answer:1,
   q:"Two features are strongly correlated (x₂ ≈ x₁). Lasso tends to",
   opts:[
     {txt:"keep both, with equal-sized weights, because that is min ‖w‖₂.",
      hint:"Min ‖w‖₂ among interpolators is ridge / min-norm. Lasso's L1 ball prefers a vertex."},
     {txt:"pick one and zero the other (or, with elastic net, split the credit).", hint:""},
     {txt:"zero both, because correlated features are collinear and XᵀX is singular.",
      hint:"Collinearity does not force the data term to ignore both. OLS is unstable; lasso still wants some fit."},
     {txt:"become identical to dropout.",
      hint:"Dropout zeros activations randomly per step; it does not solve a lasso problem on w."}],
   why:"The L1 ball's vertices are axis-aligned. When two features explain the same thing, a vertex that keeps only one is cheaper in ‖w‖₁ than a face that keeps both. Elastic net (L1 + L2) was invented to share credit between correlated features."},
  {t:"answer", html:"<p>Draw the diamond. Remember S_λ. On table B, λ = 2 is already enough to delete x₂. That is the thing L2 will not do for you at any finite λ.</p>"}
 ]},

{n:4, eyebrow:"part 4", title:"Dropout",
 result:"train a random subnetwork each step; at test, use the full net (inverted dropout)",
 blocks:[
  {t:"hook", q:"Instead of deleting a weight forever, what if we delete a random hidden unit for one step?",
   hint:"Srivastava et al. 2014; Goodfellow §7.12."},
  {t:"p", html:"{t:dropout} is regularisation by noise in the activations. For each training example (or minibatch step), draw a binary mask m_i ~ Bernoulli(p) independently for specified units, usually hidden. Those units with m_i = 0 contribute nothing to the forward pass, and they receive no gradient. The stored weights still exist; they are just ignored this step."},
  {t:"p", html:"Prince (UDL figs. 9.8–9.9) draws the mechanism: dropout breaks co-adaptation. A hidden unit cannot assume that a particular neighbour will be present, so it cannot rely on a fragile cancellation (a kink in the function that needs two units in concert). Each unit has to be useful in many random subsets."},
  {t:"raw", html: figHTML("figs/udl_fig98_dropout.png",
    "Prince, Understanding Deep Learning, fig. 9.8 — a network and three random thinned copies. Grey nodes are dropped for that step.")},
  {t:"raw", html: figHTML("figs/udl_fig99_dropout_mech.png",
    "Prince, fig. 9.9 — why co-adaptation is the enemy: a sequential up-then-down in slope is a kink that needs two units acting together. Dropout makes that conspiracy unreliable.")},
  {t:"raw", html: figHTML("figs/gdl_fig76_dropout.png",
    "Goodfellow et al., fig. 7.6 — dropout as an ensemble of all 2ⁿ subnetworks that share weights. Test time approximates the geometric mean of that ensemble.")},
  {t:"raw", html: figHTML("figs/dlfc_fig917_dropout.png",
    "Bishop & Bishop, fig. 9.17 — a full net and two pruned realisations. Their §9.6.1 identifies dropout with model averaging.")},
  {t:"h3", html:"Inverted dropout, done with a calculator"},
  {t:"p", html:"If you drop units at train and then use the full net at test, every activation is systematically larger at test (more units present). The original paper multiplied leftover weights by p at test. {t:inverted_dropout} does the scale in training instead: divide by p when a unit is kept. Test is then a plain forward pass. Table D uses p = 0.5, so kept units double."},
  {t:"raw", html: T_DROP()},
  {t:"math", html:"h̃ = (m ⊙ h) / p"},
  {t:"blank", id:"D1a"},
  {t:"blank", id:"D1b"},
  {t:"blank", id:"D2"},
  {t:"blank", id:"D3"},
  {t:"anim", id:"r4", title:"Visualiser 4 · a four-unit hidden layer under dropout",
   intro:"Each play-step draws a new Bernoulli mask at the current keep probability p. Bars: raw h (grey) and forwarded h̃ (amber). At p = 1 the two coincide. Toggle test mode: mask off, no 1/p (inverted convention)."},
  {t:"card", v:"cream", html:
    "<h4>Practical notes</h4>" +
    "<ul class=\"lines\">" +
    "<li>Typical {t:keep_probability}: 0.8–0.9 on inputs, 0.5–0.8 on hidden. p is a {t:hyperparameters}.</li>" +
    "<li>Dropout on the output layer is unusual (it noises the actual prediction).</li>" +
    "<li>With {t:batch_norm}, many modern conv nets drop dropout; residual nets already have their own noise and averaging. Transformers still drop, in attention and residual branches.</li>" +
    "<li>MC dropout (keep dropping at test, average many masks) is a cheap Bayesian-ish uncertainty estimate. That is not the default.</li>" +
    "</ul>"},
  {t:"mcq", tag:"part 4 · question 4", answer:3,
   q:"A unit has incoming weights that only cancel a partner unit's output. After dropout training, this conspiracy is",
   opts:[
     {txt:"reinforced, because the partner is always there at test.",
      hint:"Test uses the full net, but training never rewarded the conspiracy: the partner was often missing."},
     {txt:"an L1 feature: those weights will be exactly zero.",
      hint:"Dropout does not solve a lasso problem. Weights stay dense; activations are sparse per step."},
     {txt:"the definition of residual learning.",
      hint:"Residuals are a different trick (identity skip)."},
     {txt:"discouraged: the unit had to be useful in subsets where the partner was dropped.", hint:""}],
   why:"Prince's kink picture. Dropout is an explicit attack on co-adaptation, which is a particular kind of {t:overfitting}."},
  {t:"answer", html:"<p>Training: mask, scale by 1/p. Test: full net, no mask. Interpret as a cheap ensemble of thinned nets that share w. p is the knob; smaller p is stronger {t:regularisation}.</p>"}
 ]},

{n:5, eyebrow:"part 5", title:"Batch normalisation",
 result:"normalise each channel over the minibatch, then γ û + β; at test use running stats",
 blocks:[
  {t:"hook", q:"If a hidden unit's values wander from 0.01 to 50 as earlier layers train, what can the next layer do?",
   hint:"Standardise, then let the net undo it with two parameters."},
  {t:"p", html:"{t:batch_norm} (Ioffe & Szegedy 2015) inserts, for each scalar channel, a normalisation over the current minibatch, then a learned {t:scale_shift}. Bishop & Bishop §7.4.2 treat it next to data normalisation: the same idea, applied to hidden variables that keep moving. Prince §11.4 puts it in the residual-net chapter, because BN is how very deep residual stacks stay trainable."},
  {t:"math", big:true, html:"{mu}_B = (1/m) Σ_i u_i, &nbsp; σ_B² = (1/m) Σ_i (u_i − {mu}_B)²"},
  {t:"math", html:"û_i = (u_i − {mu}_B) / √(σ_B² + {eps}), &nbsp; y_i = {gamma} û_i + {beta}"},
  {t:"p", html:"m is the batch size, {eps} a tiny constant for stability (10⁻⁵). {gamma} and {beta} are trainable, one pair per channel. If the net wants the identity, it can set {gamma} = √(σ²+ε) and {beta} = μ — so BN does not force every layer to zero-mean unit-variance features, it only makes that the default around which learning happens."},
  {t:"raw", html: figHTML("figs/dlfc_batchnorm.png",
    "Bishop & Bishop, §7.4.2 / fig. 7.8 — batch normalisation in the hidden pipeline. Statistics are computed per channel across the batch.")},
  {t:"raw", html: figHTML("figs/udl_fig1115_bn_graph.png",
    "Prince, fig. 11.15 — computational graph of BN (problem 11.5 in UDL). Mean and variance are functions of the whole batch, so the gradient of y_i depends on every u_j.")},
  {t:"raw", html: figHTML("figs/udl_fig1114_norm.png",
    "Prince, fig. 11.14 — BatchNorm versus LayerNorm / InstanceNorm / GroupNorm. BN aggregates across batch and spatial axes, per channel. The others exist because BN is awkward at batch size 1 (transformers, style transfer, small-GPU fine-tunes).")},
  {t:"h3", html:"Four numbers, one unit, one batch"},
  {t:"p", html:"Table C. One hidden unit, batch size 4, ε = 0 so the arithmetic is visible, then {gamma} = 2, {beta} = 1. Use the population variance (divide by N = 4), matching the BN forward pass — not the unbiased N−1 estimator."},
  {t:"raw", html: T_BN()},
  {t:"worked", tag:"batch of four", title:"μ, σ², û, then γ û + β",
   lines:[
     "μ_B = (1+3+5+7)/4 = 4",
     "σ_B² = (9+1+1+9)/4 = 5,   √5 ≈ 2.2361",
     "û = (−3, −1, +1, +3) / 2.2361 ≈ (−1.3416, −0.4472, +0.4472, +1.3416)",
     "y = 2 û + 1 ≈ (−1.6832, 0.1056, 1.8944, 3.6832)"
   ],
   note:"Mean of û is 0; mean of y is β = 1. Variance of û is 1; variance of y is γ² = 4. The next layer sees a stable location and scale, plus whatever γ, β learned."},
  {t:"blank", id:"B1"},
  {t:"blank", id:"B2"},
  {t:"blank", id:"B3"},
  {t:"blank", id:"B4"},
  {t:"h3", html:"Train versus test"},
  {t:"p", html:"μ_B and σ_B² are properties of whoever else is in the minibatch. A test example of size 1 has no such companions. The standard fix is {t:running_stats}: exponential moving averages of mean and variance, updated at every training step, frozen at test. Forgetting to switch the module to eval is a classic bug — predictions then change if you shuffle the test set."},
  {t:"blank", id:"B5"},
  {t:"p", html:"Two stories for why BN helps. Ioffe & Szegedy: it reduces {t:internal_covariate} shift. Santurkar et al. (2018): it smooths the loss, so gradient descent is better conditioned. Prince records both. Operationally you need neither story to implement the four lines above."},
  {t:"anim", id:"r5", title:"Visualiser 5 · a batch sliding through BN",
   intro:"Four activations (dots). Vertical line: μ_B. Band: ±σ_B. Amber dots: y = γ û + β. Drag the fourth example to wreck the batch mean; drag γ and β to see scale-and-shift recover a useful range. Toggle 'test (running stats)' to freeze μ, σ at the values from the default batch."},
  {t:"card", v:"cream", html:
    "<h4>What BN is not</h4>" +
    "<p class=\"txt\">It is not L2. It is not a sparsity prior. It <em>is</em> a regulariser in the Goodfellow sense: the batch noise (μ_B, σ_B² jumping every step) makes training less able to memorise. Smaller batches → noisier BN → often more regularisation, worse estimate of μ, σ. Very small batches are why LayerNorm won in transformers.</p>"},
  {t:"mcq", tag:"part 5 · question 5", answer:2,
   q:"You train with batch size 64 and BN. At test you pass one image at a time, but you leave the module in train mode. What happens?",
   opts:[
     {txt:"Nothing: inverted BN, like inverted dropout, has already scaled.",
      hint:"BN's test fix is running averages, not a 1/p scale."},
     {txt:"Every prediction is exactly γ · 0 + β = β, because a batch of 1 has σ = 0.",
      hint:"A batch of 1 has σ = 0, which is why ε exists — but train-mode with size 1 is still ill-posed / noisy, and if you somehow batched test images, each image's neighbours would leak."},
     {txt:"Each prediction depends on whichever other examples share its (possibly size-1) batch; it will not match the running-average network you think you trained.", hint:""},
     {txt:"Dropout turns off automatically, so BN must too.",
      hint:"The two modules have independent train/eval flags."}],
   why:"Eval mode + running statistics is part of the definition of {t:batch_norm}, not an optional extra."},
  {t:"answer", html:"<p>Forward: centre, divide by batch std, then {gamma} û + {beta}. Backward: everyone in the batch is coupled through μ and σ. Test: freeze those to {t:running_stats}. {gamma}, {beta} remain live parameters.</p>"}
 ]},

{n:6, eyebrow:"part 6", title:"Early stopping",
 result:"stop at the validation minimum; time is a regulariser",
 blocks:[
  {t:"hook", q:"If longer training drives training loss down, why is the last epoch often the wrong one to ship?",
   hint:"The validation curve turns up while the training curve is still falling."},
  {t:"p", html:"{t:early_stopping} is the regulariser you already use whenever you plot two curves. Goodfellow §7.8: as optimisation proceeds, {t:training_loss} falls; {t:validation_set} loss typically falls, then rises. The rise is {t:overfitting} in time rather than in width. Save θ at the validation minimum (plus a patience window so you do not stop on noise), and restore that checkpoint."},
  {t:"raw", html: figHTML("figs/gdl_fig73_earlystop.png",
    "Goodfellow et al., fig. 7.3 — training NLL keeps falling; validation NLL minimises and then rises. The vertical gap at the far right is wasted capacity spent on the sample.")},
  {t:"raw", html: figHTML("figs/gdl_earlystop_param.png",
    "Goodfellow et al., §7.8 — early stopping as a constraint on the path length of gradient descent. Parameters start at θ₀ and walk; stopping truncates the walk. This is why Bishop can identify early stopping with a form of L2 for linear models.")},
  {t:"raw", html: figHTML("figs/prml_fig511_earlystop.png",
    "Bishop, PRML, figs. 5.11–5.12 — training vs validation error against epochs, and the effective number of parameters growing with training time. Stopping time ≈ a {t:effective_parameters} budget.")},
  {t:"raw", html: figHTML("figs/udl_fig96_earlystop.png",
    "Prince, fig. 9.6 — a small network trained past the useful point: the fit grows extra wiggles. Early stopping is the snapshot before those wiggles.")},
  {t:"raw", html: figHTML("figs/dlfc_earlystop.png",
    "Bishop & Bishop, §9.3.1 — early stopping in the regularisation chapter, next to weight decay. The two knobs are cousins: both limit how far θ may travel from a small initialisation.")},
  {t:"h3", html:"The protocol, in order"},
  {t:"lines", items:[
    "Split off a {t:validation_set}. Never update θ with its gradient.",
    "Record L_val every epoch (or every k steps). Keep a copy of the best θ so far.",
    "If L_val has not improved for P epochs (patience), stop. Restore the best copy.",
    "Optionally: after choosing the stopping epoch, retrain on train+val for that many epochs, and then evaluate once on a true test set. Only do this if you can afford it and you do not peek at test during the choice.",
    "The patience P and the evaluation cadence are {t:hyperparameters}."
  ]},
  {t:"p", html:"Bishop (PRML §5.5.2) shows that for a linear net with quadratic error, early stopping is approximately {t:ridge} with λ related to 1/(training time). Intuition: GD on a quadratic is slowest along the small-eigenvalue directions — the same directions ridge damps. Stopping before those directions finish is like leaving them shrunk."},
  {t:"blank", id:"E1"},
  {t:"blank", id:"E2"},
  {t:"anim", id:"r6", title:"Visualiser 6 · train versus validation against epoch",
   intro:"A degree-9 polynomial, fit by gradient descent on the six sine points. Amber: training MSE. Navy: validation MSE on a held-out grid against the true sine. The star is the early-stopping point. Play to watch the validation curve bottom out while training is still falling. Drag the learning rate if you want a twitchier path."},
  {t:"mcq", tag:"part 6 · question 6", answer:0,
   q:"You have a test set and a validation set. You pick the checkpoint with the best test loss. The number you report is",
   opts:[
     {txt:"optimistically biased: the test set was used as a validation set.", hint:""},
     {txt:"fine, because you did not take gradients on test examples.",
      hint:"Hyperparameter / checkpoint selection overfits whichever split you select with. Gradients are not the only leak."},
     {txt:"pessimistically biased, because early stopping raises training loss.",
      hint:"Selecting the best of many test numbers overestimates future performance."},
     {txt:"equal to the Bayes error.",
      hint:"Nothing here identifies σ²."}],
   why:"Same sermon as λ-selection on the previous sheet. Checkpoint index is a {t:hyperparameters}. The split that chose it is a {t:validation_set}."},
  {t:"answer", html:"<p>Two curves. Stop on the held-out one. Time is {t:capacity}. For linear models that statement can be made into an equivalence with {t:l2}; for deep nets it remains a robust, cheap regulariser that composes with all the others.</p>"}
 ]},

{n:7, eyebrow:"part 7", title:"Which knob, and in what order",
 result:"L1 selects, L2 shrinks, dropout noises activations, BN stabilises, early stopping truncates time",
 blocks:[
  {t:"hook", q:"Five methods, one gap. How do you not turn them all up at once until the model underfits?",
   hint:"They are not interchangeable, and several already regularise as a side effect."},
  {t:"p", html:"A usable default for a modern residual conv net: {t:batch_norm} (or LayerNorm) on, {t:weight_decay} of order 10⁻⁴, {t:early_stopping} on a validation split, dropout only if you still overfit. A linear model on many correlated features: {t:lasso} or elastic net, not dropout. A transformer: LayerNorm, residual dropout, weight decay, early stopping. The architecture already is a regulariser ({t:inductive_bias} of convolution, residual identity, attention). Penalties sit on top."},
  {t:"strip", html:"<span class=\"sl\">a one-line map</span>L1 deletes weights · L2 shrinks weights · dropout deletes activations at train · BN re-scales activations · early stopping deletes training time"},
  {t:"blank", id:"C1"},
  {t:"blank", id:"C2"},
  {t:"mcq", tag:"part 7 · question 7", answer:1,
   q:"Training loss is high and validation loss is equally high. You currently use λ = 10 on a small net, dropout p = 0.2, and you stopped at epoch 2 of 200. The most plausible diagnosis is",
   opts:[
     {txt:"overfitting; increase λ and lower p.",
      hint:"Train is already high. More regularisation will not invent capacity."},
     {txt:"underfitting (or unfinished optimisation). Relax the regularisers and train longer.", hint:""},
     {txt:"batch norm in train mode at test, exclusively.",
      hint:"That would typically hurt test more than train."},
     {txt:"the validation set leaking into training.",
      hint:"Leakage usually makes validation look too good, not too bad."}],
   why:"High train + high val is {t:underfitting}, or a learning-rate / initialisation failure. The regularisers on this sheet are innocent until train is low and val is not."},
  {t:"answer", html:"<p>Read the pair (L_train, L_val) first. High–high: capacity or optimisation. Low–high: regularise, or stop earlier, or add data. Then pick the tool that matches the model class — sparsity, shrinkage, noise, scale, or time.</p>"}
 ]},

{n:8, eyebrow:"retrieval", title:"Eight questions, no new arithmetic",
 result:"definitions, not tricks",
 blocks:[
  {t:"p", html:"Open any {t:l1} / {t:l2} / {t:dropout} / {t:batch_norm} / {t:early_stopping} bubble if a word has gone cold."},
  {t:"mcq", tag:"retrieval · 1", answer:0,
   q:"Ridge's closed form replaces XᵀX with",
   opts:[
     {txt:"XᵀX + λI.", hint:""},
     {txt:"XᵀX − λI.", hint:"That would be even more singular."},
     {txt:"|XᵀX|, an L1 matrix.", hint:"L1 is not a closed-form modification of XᵀX."},
     {txt:"the identity, ignoring the data.", hint:"Only as λ → ∞."}],
   why:"Eigenvalues shift by λ. That is both the numerical fix and the {t:shrinkage}."},
  {t:"mcq", tag:"retrieval · 2", answer:2,
   q:"L1 tends to produce exact zeros because",
   opts:[
     {txt:"the L1 ball is a circle, and circles hit the axes.",
      hint:"Circles are L2."},
     {txt:"the gradient of |w| at 0 is 0, so weights freeze.",
      hint:"The subgradient at 0 is [−1, 1], not {0}. Freezing happens when the data gradient lies inside that interval."},
     {txt:"the constraint region has corners on the axes, and |w| has a subgradient interval at 0 that the data term must overcome.", hint:""},
     {txt:"SGD rounding error eventually underflows small weights.",
      hint:"Sparsity is in the exact objective, not a numerical accident. Ridge does not underflow to exact zeros."}],
   why:"Geometry plus the proximal map S_λ."},
  {t:"mcq", tag:"retrieval · 3", answer:1,
   q:"Inverted dropout with keep probability p, at test time,",
   opts:[
     {txt:"drops units with probability 1−p, matching training.",
      hint:"Test is deterministic in the default algorithm."},
     {txt:"uses the full network with no extra scaling, because training already divided by p.", hint:""},
     {txt:"multiplies outputs by 1/p.",
      hint:"That would double-scale if training already divided by p."},
     {txt:"replaces p with the running average of p.",
      hint:"That is mixing up dropout with BN."}],
   why:"{t:inverted_dropout} moves the scale to training so test is boring — which is what you want."},
  {t:"mcq", tag:"retrieval · 4", answer:3,
   q:"In the BN forward pass, σ_B² is usually",
   opts:[
     {txt:"the unbiased sample variance with / (m−1), matching numpy.var(ddof=1).",
      hint:"The paper uses / m, then adds ε."},
     {txt:"always 1, because γ will learn the scale.",
      hint:"You still divide by the current batch std; γ is extra."},
     {txt:"computed across all channels together.",
      hint:"Standard BN is per channel (and across batch / spatial)."},
     {txt:"(1/m) Σ (u_i − μ_B)², then you add ε under the square root.", hint:""}],
   why:"Table C used / 4, not / 3, for that reason."},
  {t:"mcq", tag:"retrieval · 5", answer:1,
   q:"BN at test time needs running averages because",
   opts:[
     {txt:"γ and β are not defined for a single example.",
      hint:"γ, β are parameters, independent of batch size."},
     {txt:"μ_B and σ_B² are not defined (or are degenerate) for a single example, and should not depend on whoever else is in a test batch.", hint:""},
     {txt:"dropout's mask must be averaged too.",
      hint:"Different module."},
     {txt:"otherwise L2 is applied twice.",
      hint:"BN is not L2."}],
   why:"{t:running_stats} are part of the layer."},
  {t:"mcq", tag:"retrieval · 6", answer:2,
   q:"Early stopping chooses the checkpoint that minimises",
   opts:[
     {txt:"training loss.", hint:"Training is still falling at the useful point."},
     {txt:"‖w‖₂, which is equivalent for every architecture.",
      hint:"The L2 equivalence is for certain linear / quadratic cases, not a general identity."},
     {txt:"validation loss (with patience).", hint:""},
     {txt:"test loss, after trying every epoch on the test set.",
      hint:"Then it is no longer a test set."}],
   why:"Time is a {t:hyperparameters}. Hyperparameters live on the {t:validation_set}."},
  {t:"mcq", tag:"retrieval · 7", answer:0,
   q:"Weight decay in vanilla SGD is",
   opts:[
     {txt:"the update w ← (1 − ηλ) w − η ∇E, equivalent to L2 on the loss.", hint:""},
     {txt:"identical to dropout with p = λ.",
      hint:"Different noise."},
     {txt:"a running average of w, like BN's running mean.",
      hint:"Multiplicative fade, not an EMA of weights (that would be more like Polyak averaging)."},
     {txt:"only defined for L1.",
      hint:"The classical 'weight decay' name is the L2 fade."}],
   why:"Write the gradient of E + (λ/2)‖w‖² and collect terms."},
  {t:"mcq", tag:"retrieval · 8", answer:3,
   q:"A method that raises training loss and can lower test loss is, by Goodfellow's definition,",
   opts:[
     {txt:"only L2. The others are optimisation tricks, not regularisers.",
      hint:"Chapter 7 of the Deep Learning book includes dropout, early stopping, BN-as-noise, and more."},
     {txt:"overfitting.",
      hint:"Overfitting is the disease. These are treatments."},
     {txt:"double descent.",
      hint:"A shape of a curve, not a training method."},
     {txt:"regularisation.", hint:""}],
   why:"That sentence is how this sheet started. All five tools sit under it."}
 ]}
];
