/* =========================================================================
   GLOSSARY.  {t:key} in any string becomes the term plus an info bubble.
   ========================================================================= */
var GLOSS = {
  underfitting:{
    term:"underfitting",
    def:"The model is too simple for the true pattern. Training error stays high, and test error is high for the same reason: the hypothesis class cannot represent f even with infinite data.",
    formula:"high bias, low variance",
    see:"Goodfellow, Bengio & Courville, Deep Learning (2016), §5.2; Bishop, PRML (2006), §1.1."
  },
  overfitting:{
    term:"overfitting",
    def:"The model fits the training sample, including noise, so training error looks excellent while error on new draws from the same process is worse. Classic sign: a large generalisation gap.",
    formula:"low train loss, high test loss",
    see:"Goodfellow et al., §5.2; Bishop, PRML, §1.1 (polynomial curve fitting)."
  },
  generalisation:{
    term:"generalisation",
    def:"How well a fitted model predicts new examples drawn from the same distribution as the training data. The thing we actually want. Training loss is only a proxy.",
    see:"Goodfellow et al., §5.2; Prince, Understanding Deep Learning, ch. 20."
  },
  generalisation_gap:{
    term:"generalisation gap",
    def:"The difference between test loss and training loss. A large gap usually means the model memorised idiosyncrasies of the sample. A small gap with high loss usually means underfitting.",
    formula:"gap = L_test − L_train",
    see:"Goodfellow et al., §5.2."
  },
  training_loss:{
    term:"training loss",
    def:"Average loss on the examples the optimiser was allowed to see. Also called empirical risk. Can be driven to zero by a model that merely interpolates the sample.",
    formula:"L_train(θ) = (1/N) Σᵢ ℓ(yᵢ, fθ(xᵢ))",
    see:"Bishop & Bishop, Deep Learning (2023), ch. 4; Goodfellow et al., §5.1."
  },
  test_loss:{
    term:"test loss",
    def:"Average loss on a held-out sample that was not used to fit parameters or to choose hyperparameters. An estimate of expected risk. Keep it untouched until the end.",
    formula:"L_test ≈ E_{x,y}[ℓ(y, fθ(x))]",
    see:"Goodfellow et al., §5.3."
  },
  expected_risk:{
    term:"expected risk",
    def:"The loss you would get if you could average over the true data-generating process, not just a finite sample. Training loss estimates this from the same points used for fitting, so it is optimistically biased.",
    formula:"R(θ) = E_{x,y}[ℓ(y, fθ(x))]",
    see:"Bishop, PRML, §1.5.5; Goodfellow et al., §5.2."
  },
  capacity:{
    term:"capacity",
    def:"How large a family of functions the model can represent. Polynomial degree, number of hidden units, and number of parameters are crude proxies. Too little capacity underfits; too much can overfit — until double descent.",
    see:"Goodfellow et al., §5.2 (VC dimension, representational capacity)."
  },
  hypothesis_class:{
    term:"hypothesis class",
    def:"The set of functions the learning algorithm is allowed to choose from. Constants, lines, degree-M polynomials, and a given neural architecture are four different classes.",
    formula:"ℋ = { fθ : θ ∈ Θ }",
    see:"Goodfellow et al., §5.2."
  },
  interpolation:{
    term:"interpolation",
    def:"A fit that passes through every training point, so training loss is exactly zero (for squared loss, if the points are distinct). With N scalar targets you typically need at least N free parameters.",
    formula:"fθ(xᵢ) = yᵢ  for all i",
    see:"Belkin et al. (2019); Bishop & Bishop (2023), §9.3.2."
  },
  interpolation_threshold:{
    term:"interpolation threshold",
    def:"The model size where the number of effective parameters first matches the number of training points. Test error often peaks here: the model is just able to interpolate, and does so unstably. Past this point, more parameters can help again.",
    formula:"P ≈ N",
    see:"Bishop & Bishop (2023), §9.3.2; Nakkiran et al., Deep Double Descent (2020)."
  },
  bias:{
    term:"bias",
    def:"How far the average predictor (average over training sets of the same size) sits from the true function. A constant model predicting 3 when the mean is 5 has bias −2, no matter how much data you give it, if it cannot change.",
    formula:"Bias(x) = E_D[f̂_D(x)] − f(x)",
    see:"Bishop, PRML, §3.2; Bishop & Bishop (2023), §4.3; Goodfellow et al., §5.4."
  },
  variance:{
    term:"variance",
    def:"How much the fitted function jumps when you redraw the training set. High-capacity interpolators have high variance: each sample of noise is written into the function.",
    formula:"Var(x) = E_D[(f̂_D(x) − E_D[f̂_D(x)])²]",
    see:"Bishop, PRML, §3.2; Goodfellow et al., §5.4."
  },
  irreducible_error:{
    term:"irreducible error",
    def:"The leftover risk even with the best possible predictor: noise in y, or any part of y that is not a function of x. Also called Bayes error (for classification) or noise variance σ² (for squared loss).",
    formula:"σ² = E[(y − f(x))²]",
    see:"Bishop, PRML, §3.2; Goodfellow et al., §5.4.4."
  },
  bias_variance:{
    term:"bias–variance trade-off",
    def:"For squared loss, expected test error splits into irreducible error + bias² + variance. Making the model more flexible typically lowers bias and raises variance. The U-shaped test curve is this trade-off plotted against capacity.",
    formula:"E[(y − f̂)²] = σ² + Bias² + Variance",
    see:"Bishop, PRML, §3.2; Bishop & Bishop (2023), §4.3."
  },
  double_descent:{
    term:"double descent",
    def:"Test error falls, then rises toward the interpolation threshold, then falls again as the model becomes overparameterised. The second descent is outside classical U-shaped thinking: more parameters can improve test error after the model already interpolates.",
    see:"Bishop & Bishop (2023), §9.3.2; Prince, UDL, §20.2 (overparameterisation); Belkin et al. (2019)."
  },
  overparameterised:{
    term:"overparameterised",
    def:"More parameters than training points (P > N). The training loss can be driven to zero in many ways; which interpolator you land on depends on architecture, init, and the optimiser. Often the implicit bias of SGD picks a surprisingly good one.",
    formula:"P > N",
    see:"Prince, UDL, §20.2; Bishop & Bishop (2023), §9.3."
  },
  regularisation:{
    term:"regularisation",
    def:"Any extra preference that stops the fit from using its full capacity. Weight decay, early stopping, dropout, and data augmentation are all regularisers. In bias–variance language they usually raise bias a little to cut variance a lot.",
    see:"Goodfellow et al., ch. 7; Bishop & Bishop (2023), ch. 9; Bishop, PRML, §1.1 (the penalty λ)."
  },
  weight_decay:{
    term:"weight decay",
    def:"Add λ‖θ‖² to the loss (ridge / L2). Large λ shrinks coefficients toward zero and recovers a simpler function. λ = 0 is unregularised least squares.",
    formula:"L_λ(θ) = L_train(θ) + λ ‖θ‖²",
    see:"Bishop, PRML, §3.1.4; Goodfellow et al., §7.1."
  },
  validation_set:{
    term:"validation set",
    def:"A split used to choose hyperparameters (degree, λ, architecture) but not to update θ by gradient descent. If you tune on the test set, the test number is no longer an honest estimate of expected risk.",
    see:"Goodfellow et al., §5.3."
  },
  hyperparameters:{
    term:"hyperparameters",
    def:"Choices that are not fitted by the inner optimiser: polynomial degree, λ, learning rate, width, depth. You select them on validation data, then report test loss once.",
    see:"Goodfellow et al., §5.3."
  },
  inductive_bias:{
    term:"inductive bias",
    def:"The assumptions a learner makes in order to generalise at all. Convolution assumes locality and translation structure; a line assumes the world is linear. No free lunch: some bias is required.",
    see:"Bishop & Bishop (2023), §9.1; Goodfellow et al., §5.2."
  },
  mse:{
    term:"mean squared error",
    def:"Average of squared residuals. For regression it is the usual training loss, and the bias–variance decomposition is derived for this loss (not for 0–1 loss).",
    formula:"MSE = (1/N) Σᵢ (yᵢ − ŷᵢ)²",
    see:"Bishop, PRML, §1.1; Goodfellow et al., §5.2."
  },
  least_squares:{
    term:"least squares",
    def:"Choose parameters that minimise mean squared error on the training set. For a linear-in-parameters model this is a linear system; for a polynomial of degree M it is least squares in the monomial basis.",
    formula:"θ̂ = arg min_θ ‖y − Φθ‖²",
    see:"Bishop, PRML, §3.1."
  },
  effective_parameters:{
    term:"effective parameters",
    def:"How many degrees of freedom the fit actually uses, after regularisation. Ridge with large λ can make a 100-parameter model behave like a 3-parameter one. Double descent is about effective capacity, not just the count of weights.",
    see:"Bishop, PRML, §3.5.3 (effective number of parameters); Bishop & Bishop (2023), §9.3."
  },
  early_stopping:{
    term:"early stopping",
    def:"Halt gradient descent before training loss bottoms out, using a validation curve. It acts like a regulariser: the optimiser has not had time to fit every noise wiggle.",
    see:"Goodfellow et al., §7.8."
  },
  memorisation:{
    term:"memorisation",
    def:"Fitting labels, even random labels, by interpolating the sample. Overparameterised nets can do this and still generalise on the true labelling — one of the facts that forced double descent into the textbooks.",
    see:"Prince, UDL, §20.2; Zhang et al. (2017), Understanding deep learning requires rethinking generalisation."
  }
};

var BLANKS = [
{id:"G1", sec:1, wide:true,
 prompt:"Training loss is computed on points the model {slot}.",
 need:["the definition of training vs test"],
 correct:"was allowed to fit",
 options:["was allowed to fit","must never see","are drawn from a different task"],
 hints:{"must never see":"That is the test (or validation) set. Training loss is the number the optimiser sees.",
        "are drawn from a different task":"Train and test are assumed to come from the same process. That is the whole point of generalisation."}},
{id:"G2", sec:1, wide:true,
 prompt:"Test loss estimates {slot}.",
 need:["why we hold data out"],
 correct:"expected risk on new draws from the same process",
 options:["expected risk on new draws from the same process",
          "how well we memorised the training labels",
          "the number of parameters"],
 hints:{"how well we memorised the training labels":"That is training loss, especially after interpolation.",
        "the number of parameters":"Capacity is a property of the hypothesis class, not a loss."}},
{id:"G3", sec:1,
 prompt:"gap = L_test − L_train = 1.2500 − 0.6667 = {{slot}}",
 need:["L_train = 0.6667 for the constant","L_test = 1.2500 for the constant"],
 correct:"0.5833",
 options:["0.5833","1.9167","0.6667","1.2500"],
 hints:{"1.9167":"Subtract, do not add.",
        "0.6667":"That is L_train alone.",
        "1.2500":"That is L_test alone."}},
{id:"U1", sec:2,
 prompt:"c = (1 + 2 + 0) / 3 = {{slot}}",
 need:["three training y values: 1, 2, 0"],
 correct:"1",
 options:["1","2","0","1.5"],
 hints:{"2":"That is one of the y values, not the mean.",
        "0":"That is the last y, not the mean.",
        "1.5":"(1+2+0)/3 = 3/3 = 1, not 3/2."}},
{id:"U2a", sec:2, lab:"residual at x = 0",
 need:["c = 1","y = 1, 2, 0"],
 correct:"0",
 options:["0","−1","+1","+2"],
 hints:{"−1":"residual = y − c. At x = 0, y is 1.",
        "+1":"At x = 0, y equals c.",
        "+2":"That is y at x = 1."}},
{id:"U2b", sec:2, lab:"residual at x = 1",
 correct:"+1",
 options:["+1","0","−1","+2"],
 hints:{"0":"y is 2, c is 1.",
        "−1":"Sign: 2 − 1 is positive.",
        "+2":"That is y, not y − c."}},
{id:"U2c", sec:2, lab:"residual at x = 2",
 correct:"−1",
 options:["−1","+1","0","−2"],
 hints:{"+1":"y is 0, c is 1, so 0 − 1 is negative.",
        "0":"The constant does not hit this point.",
        "−2":"0 − 1 = −1."}},
{id:"U3", sec:2,
 prompt:"L_train = (0² + 1² + (−1)²) / 3 = {{slot}}",
 need:["residuals 0, +1, −1"],
 correct:"0.6667",
 options:["0.6667","0.0000","1.0000","2.0000"],
 hints:{"0.0000":"Two of the three residuals are not zero. Average the squares.",
        "1.0000":"You averaged |residual| or took 3/3. Squares: (0+1+1)/3.",
        "2.0000":"You summed the squares and forgot to divide by 3."}},
{id:"U4", sec:2, wide:true,
 prompt:"The constant cannot follow the dip from y = 2 down to y = 0. That limitation is {slot}.",
 need:["L_train = 0.6667 is not zero"],
 correct:"bias: the class is too small",
 options:["bias: the class is too small",
          "variance: the class is too large",
          "irreducible error: y is a deterministic function of these x",
          "a bug in the mean"],
 hints:{"variance: the class is too large":"A constant has almost no variance across datasets. It is too small a class.",
        "irreducible error: y is a deterministic function of these x":"There is no extra noise term in table A. The mismatch is the model.",
        "a bug in the mean":"The mean of 1, 2, 0 really is 1."}},
{id:"O1a", sec:3, lab:"from x = 0",
 need:["ŷ(x) = 1 + 2.5 x − 1.5 x²","the curve must hit (0,1), (1,2), (2,0)"],
 correct:"1",
 options:["1","2.5","−1.5","0"],
 hints:{"2.5":"That is the coefficient of x.",
        "−1.5":"That is the coefficient of x².",
        "0":"ŷ(0) = a = 1."}},
{id:"O1b", sec:3, lab:"from x = 1, using a = 1",
 correct:"1",
 options:["1","2","0","1.5"],
 hints:{"2":"That is y at x = 1. The equation is 1 + b + c = 2, so b + c = 1.",
        "0":"That would be 1 + b + c = 1.",
        "1.5":"b + c = 2 − 1 = 1."}},
{id:"O1c", sec:3, lab:"from x = 2, using a = 1",
 correct:"−1",
 options:["−1","0","−5","1"],
 hints:{"0":"1 + 2b + 4c = 0, so 2b + 4c = −1.",
        "−5":"That is ŷ(3), which you do not know yet.",
        "1":"The right-hand side is 0 − 1 = −1."}},
{id:"O2a", sec:3, lab:"c, the x² coefficient",
 need:["b + c = 1","2b + 4c = −1"],
 correct:"−1.5",
 options:["−1.5","1.5","−0.5","2.5"],
 hints:{"1.5":"Sign. Substituting b = 1 − c into 2b + 4c = −1 gives 2 + 2c = −1, so c = −1.5.",
        "−0.5":"2(1 − c) + 4c = 2 + 2c = −1, so 2c = −3.",
        "2.5":"That is b, not c."}},
{id:"O2b", sec:3, lab:"b, the x coefficient",
 correct:"2.5",
 options:["2.5","−1.5","1.0","−2.5"],
 hints:{"−1.5":"That is c. b = 1 − c = 1 − (−1.5).",
        "1.0":"That is a, or the sum b + c.",
        "−2.5":"b = 1 − c is positive."}},
{id:"O3", sec:3,
 prompt:"ŷ(3) = 1 + 2.5(3) − 1.5(9) = 1 + 7.5 − 13.5 = {{slot}}",
 need:["a = 1","b = 2.5","c = −1.5","the test x = 3"],
 correct:"−5",
 options:["−5","0.5","1","7.5"],
 hints:{"0.5":"That is the test y at x = 3, not the model's prediction.",
        "1":"That is ŷ(0), or the constant model.",
        "7.5":"You stopped after 2.5 × 3. Subtract 1.5 × 9."}},
{id:"O4", sec:3,
 prompt:"test squared error at x = 3: (−5 − 0.5)² = {{slot}}",
 need:["ŷ(3) = −5","y_test = 0.5"],
 correct:"30.2500",
 options:["30.2500","5.5000","−5.5000","0.2500"],
 hints:{"5.5000":"You took the absolute residual and stopped. Square it: 5.5² = 30.25.",
        "−5.5000":"A square cannot be negative.",
        "0.2500":"That would be (0.5 − 0)², as if ŷ were 0."}},
{id:"O5", sec:3, wide:true,
 prompt:"Train MSE of the quadratic is 0. Test squared error at x = 3 is 30.25. This pattern is {slot}.",
 need:["the quadratic interpolates the three training points"],
 correct:"overfitting: the extra wiggle missed the new x",
 options:["overfitting: the extra wiggle missed the new x",
          "underfitting: the class is still too small",
          "perfect generalisation, because train loss is zero",
          "irreducible error, because 30.25 cannot be avoided"],
 hints:{"underfitting: the class is still too small":"Train loss is zero. The class was large enough to interpolate.",
        "perfect generalisation, because train loss is zero":"Train loss is not expected risk. Look at x = 3.",
        "irreducible error, because 30.25 cannot be avoided":"The line's test error at the same point is 0.25. The 30.25 was a choice of model."}},
{id:"B1", sec:4,
 prompt:"Bias of model A = E[ŷ] − μ = 3 − 5 = {{slot}}",
 need:["model A always predicts 3","μ = 5"],
 correct:"−2",
 options:["−2","+2","0","3"],
 hints:{"+2":"3 − 5 is negative. Bias is E[ŷ] minus the truth, not the reverse.",
        "0":"That would mean the average predictor equals μ. A's average is stuck at 3.",
        "3":"That is the prediction, not the bias."}},
{id:"B2", sec:4,
 prompt:"Bias² of model A = (−2)² = {{slot}}",
 need:["bias = −2"],
 correct:"4",
 options:["4","−4","2","0"],
 hints:{"−4":"A square is non-negative. The sign of the bias disappears.",
        "2":"Square it, do not take abs.",
        "0":"Only if the bias were zero."}},
{id:"B3", sec:4, wide:true,
 prompt:"Variance of model A across D₁, D₂, D₃ is {slot}.",
 need:["ŷ is 3, 3, 3"],
 correct:"0, because the prediction never moves",
 options:["0, because the prediction never moves",
          "4, the same as bias²",
          "1, the noise variance",
          "2, the spread of the datasets"],
 hints:{"4, the same as bias²":"Bias² is about distance to μ. Variance is about distance to E[ŷ]. Here E[ŷ] = 3 = ŷ always.",
        "1, the noise variance":"σ² is a separate term. A's prediction does not use the data, so it has no variance.",
        "2, the spread of the datasets":"The datasets change. Model A ignores them."}},
{id:"B4a", sec:4, lab:"E[ŷ] for model B",
 need:["predictions 4, 6, 5","μ = 5"],
 correct:"5",
 options:["5","4","6","4.5"],
 hints:{"4":"That is D₁ alone. Average 4, 6 and 5.",
        "6":"That is D₂ alone.",
        "4.5":"That is model C's average, not B's."}},
{id:"B4b", sec:4, lab:"bias of model B",
 correct:"0",
 options:["0","−1","+1","−2"],
 hints:{"−1":"E[ŷ] = 5 = μ.",
        "+1":"E[ŷ] = 5 = μ.",
        "−2":"That was model A."}},
{id:"B5", sec:4,
 prompt:"Variance of B = [(4−5)² + (6−5)² + (5−5)²] / 3 = {{slot}}",
 need:["E[ŷ] = 5","predictions 4, 6, 5"],
 correct:"0.6667",
 options:["0.6667","2.0000","1.0000","0.0000"],
 hints:{"2.0000":"You summed 1+1+0 and forgot to divide by 3.",
        "1.0000":"That is σ², given separately, or (1+1+0)/2 using n−1. This sheet uses the population mean over the three datasets.",
        "0.0000":"Two of the three predictions are not 5."}},
{id:"B6", sec:4,
 prompt:"Expected test error of A = σ² + Bias² + Var = 1 + 4 + 0 = {{slot}}",
 need:["σ² = 1","Bias² = 4","Var = 0"],
 correct:"5",
 options:["5","4","1","0"],
 hints:{"4":"You dropped σ².",
        "1":"You dropped Bias².",
        "0":"Add the three pieces."}},
{id:"B7", sec:4,
 prompt:"Expected test error of B = 1 + 0 + 0.6667 = {{slot}}",
 need:["σ² = 1","Bias² = 0","Var = 0.6667"],
 correct:"1.6667",
 options:["1.6667","0.6667","1.0000","5.0000"],
 hints:{"0.6667":"That is variance alone.",
        "1.0000":"That is σ² alone.",
        "5.0000":"That is model A's risk."}},
{id:"B8", sec:4, wide:true,
 prompt:"Model C shrinks each y toward 4: ŷ = ½ y + ½·4. Compared with B it should have {slot}.",
 need:["C's predictions are 4.0, 5.0, 4.5"],
 correct:"more bias, less variance",
 options:["more bias, less variance",
          "less bias, more variance",
          "the same bias and variance as B",
          "zero bias and zero variance"],
 hints:{"less bias, more variance":"Shrinkage toward 4, which is not μ = 5, adds bias and damps movement across datasets.",
        "the same bias and variance as B":"The three numbers 4, 5, 4.5 are a tighter cluster than 4, 6, 5, and their mean is 4.5, not 5.",
        "zero bias and zero variance":"Only a constant equal to μ would do that, and we cannot know μ in advance."}},
{id:"D1", sec:6, wide:true,
 prompt:"The interpolation threshold is the model size where {slot}.",
 need:["P is the number of parameters","N is the number of training points"],
 correct:"P first reaches N and train loss can hit zero",
 options:["P first reaches N and train loss can hit zero",
          "test loss is minimised",
          "bias becomes zero",
          "σ² becomes zero"],
 hints:{"test loss is minimised":"Test loss often peaks at the threshold, then falls again. The minimum can be in the overparameterised regime.",
        "bias becomes zero":"An interpolator of noise is not unbiased for f.",
        "σ² becomes zero":"Noise in y does not care how many parameters you use."}},
{id:"D2", sec:6, wide:true,
 prompt:"Past the threshold, adding parameters can {slot}. That is the second descent.",
 need:["the classical U-shape stops at interpolation"],
 correct:"lower test loss even though train loss is already ~ 0",
 options:["lower test loss even though train loss is already ~ 0",
          "raise train loss back above zero",
          "delete the irreducible error",
          "turn variance into bias"],
 hints:{"raise train loss back above zero":"Overparameterised interpolators still fit the sample. Train loss stays ~ 0; the function between the points changes.",
        "delete the irreducible error":"σ² is a property of the process, not of P.",
        "turn variance into bias":"The decomposition still adds. What changes is which interpolator you select."}},
{id:"R1", sec:7, wide:true,
 prompt:"A validation set is for {slot}.",
 need:["θ is fit on training data"],
 correct:"choosing hyperparameters without touching the test set",
 options:["choosing hyperparameters without touching the test set",
          "updating θ by gradient descent",
          "replacing the test set, so you no longer need one",
          "computing σ²"],
 hints:{"updating θ by gradient descent":"That is the training set. If you also descend on validation, it stops being a hyperparameter check.",
        "replacing the test set, so you no longer need one":"After you pick λ on validation you still need a fresh test number.",
        "computing σ²":"σ² is not something you read off a split."}}
];

var SECTIONS = [
{n:0, eyebrow:"start here", title:"How to use this sheet",
 result:"click the amber i next to a term whenever you want the definition",
 blocks:[
  {t:"lines", items:[
    "Click the option you think is right. It drops into the blank.",
    "Wrong answers grey out and give you a hint. Nothing is scored.",
    "The next step unlocks when the current one is filled.",
    "Dotted terms carry an <b>i</b> button. Open it for a one-screen definition, the formula, and the textbook section."]}
 ]},

{n:1, eyebrow:"part 1", title:"Two losses, not one",
 result:"generalisation is test behaviour, not a small training loss",
 blocks:[
  {t:"hook", q:"If training loss is almost zero, have we learned the function?",
   hint:"Three training points. Two test points. Same process."},
  {t:"p", html:"A learner is handed a finite sample and asked to predict y at x it has not seen. {t:generalisation} is that ability. The number the optimiser minimises is {t:training_loss}. The number we care about is {t:test_loss}, a stand-in for {t:expected_risk}."},
  {t:"card", v:"navy", html:
    "<div class=\"eyebrow\">the split</div>" +
    "<div class=\"mathline big\" style=\"margin:6px 0 0\">L_train(θ) &nbsp;≠&nbsp; R(θ)</div>" +
    "<p class=\"txt\" style=\"margin:10px 0 0\">The gap between them is the {t:generalisation_gap}. You cannot see it unless you hold data out.</p>"},
  {t:"raw", html:"<div class=\"tbls\">" + T_PT() + T_MODELS() + "</div>"},
  {t:"note", html:"Every calculation below uses table A. Mean squared error throughout: {t:mse}."},
  {t:"blank", id:"G1"},
  {t:"blank", id:"G2"},
  {t:"worked", tag:"constant model, already computed", title:"so you can see a gap",
   lines:[
     "c = mean of {1, 2, 0} = <b>1</b>",
     "L_train = [(1−1)² + (2−1)² + (0−1)²] / 3 = (0 + 1 + 1) / 3 = <b>0.6667</b>",
     "L_test  = [(0.5−1)² + (2.5−1)²] / 2 = (0.25 + 2.25) / 2 = <b>1.2500</b>"]},
  {t:"blank", id:"G3"},
  {t:"mcq", tag:"part 1 · question 1", answer:2,
   q:"Which statement is safe, given only L_train = 0.6667?",
   opts:[
     {txt:"The model has generalisation error 0.6667.",
      hint:"Generalisation error is expected risk, or at least test loss. You have not used the test points yet."},
     {txt:"The model is overfit, because the loss is not zero.",
      hint:"A non-zero training loss is the underfitting signature, not overfitting."},
     {txt:"You still do not know whether the constant will work on new x.", hint:""},
     {txt:"σ² must be 0.6667.",
      hint:"That number is training MSE of a particular model, not the noise of the process."}],
   why:"Training loss is a number about the sample you fitted. {t:generalisation} is a number about new draws. They are allowed to disagree, and in this sheet they will."},
  {t:"answer", html:
    "<p>Hold onto table A. Part 2 will show a model whose training loss cannot fall. Part 3 will show a model whose training loss falls to zero and whose test loss explodes. That pair is {t:underfitting} versus {t:overfitting}.</p>"}
 ]},

{n:2, eyebrow:"part 2", title:"Underfitting is a class that is too small",
 result:"a constant has high bias; averaging more data will not save it",
 blocks:[
  {t:"hook", q:"Why does the constant stop at L_train = 0.6667?",
   hint:"Its hypothesis class is a single number."},
  {t:"p", html:"{t:underfitting} means the {t:hypothesis_class} cannot represent the pattern. In bias–variance language that is {t:bias}: even the average (over datasets) of the fitted function sits far from f. {t:capacity} is too low."},
  {t:"anim", id:"a1", title:"Animation 1 · degree versus the sine",
   intro:"Six noisy points on a sine. Drag the polynomial degree. Degree 0 is the constant from this section. Watch training MSE stall high while the curve refuses to bend."},
  {t:"h3", html:"The constant, by hand"},
  {t:"blank", id:"U1"},
  {t:"blanks", ids:["U2a","U2b","U2c"], need:["c = 1"],
   prompt:"residuals y − c &nbsp; → &nbsp; {{U2a}}, &nbsp; {{U2b}}, &nbsp; {{U2c}}"},
  {t:"blank", id:"U3"},
  {t:"blank", id:"U4"},
  {t:"card", v:"cream", html:
    "<h4>What more data would do</h4>" +
    "<p class=\"txt\">If the true mean really were 1, extra samples would make c sit more firmly at 1. Training MSE would still be the scatter around 1. If the true curve is a sine, extra samples would make an even more confident <em>wrong</em> horizontal line. That is bias: it does not vanish with N.</p>"},
  {t:"mcq", tag:"part 2 · question 2", answer:1,
   q:"You switch from a constant to a line. What should happen to bias, all else equal?",
   opts:[
     {txt:"Bias rises, because you added a parameter.",
      hint:"Extra parameters enlarge the class. Bias is about whether the average fit can match f."},
     {txt:"Bias falls (or stays the same), because the line class contains the constants.", hint:""},
     {txt:"Bias becomes σ².",
      hint:"σ² is irreducible error, a property of y | x, not of the class."},
     {txt:"Bias is undefined for a line.",
      hint:"Bishop's decomposition applies to any estimator. A line fitted by least squares is an estimator."}],
   why:"Nested classes: every constant is a line with slope 0. Enlarging ℋ can only reduce the approximation error. Variance is the term that typically grows."},
  {t:"answer", html:"<p>{t:underfitting} is diagnosed by <b>high training loss</b> that extra optimisation will not fix. If gradient descent has stalled at 0.6667 because the class is a constant, you need a richer class, not a smaller learning rate.</p>"}
 ]},

{n:3, eyebrow:"part 3", title:"Overfitting is a wiggle that fitted the sample",
 result:"the unique quadratic through the three points predicts −5 at x = 3",
 blocks:[
  {t:"hook", q:"Drive training loss to zero. What happens at x = 3?",
   hint:"Three points, three parameters: a unique quadratic."},
  {t:"p", html:"{t:overfitting} is the complementary failure: {t:capacity} high enough for {t:interpolation} of the sample, including whatever in y was not the signal. Training loss looks perfect. Test loss does not."},
  {t:"strip", html:"ŷ(x) = a + b x + c x² &nbsp; must hit (0,1), (1,2), (2,0). That is three equations."},
  {t:"blanks", ids:["O1a","O1b","O1c"], need:["(0,1), (1,2), (2,0)"],
   prompt:"a = {{O1a}} &nbsp;&nbsp; b + c = {{O1b}} &nbsp;&nbsp; 2b + 4c = {{O1c}}"},
  {t:"p", html:"Substitute b = 1 − c into 2b + 4c = −1."},
  {t:"worked", tag:"algebra, if you want it spelled out", title:"",
   lines:[
     "2(1 − c) + 4c = −1",
     "2 − 2c + 4c = −1",
     "2 + 2c = −1",
     "2c = −3 &nbsp; → &nbsp; c = −1.5",
     "b = 1 − (−1.5) = 2.5"]},
  {t:"blanks", ids:["O2a","O2b"], need:["b + c = 1","2b + 4c = −1"],
   prompt:"c = {{O2a}} &nbsp;&nbsp; b = {{O2b}}"},
  {t:"note", html:"Check: ŷ(0)=1, ŷ(1)=1+2.5−1.5=2, ŷ(2)=1+5−6=0. {t:training_loss} is exactly 0."},
  {t:"anim", id:"a2", title:"Animation 2 · the interpolating wiggle",
   intro:"Same six sine points. Degree 5 interpolates all six. The curve is forced through every noisy y and then continues with whatever the monomials do next."},
  {t:"blank", id:"O3"},
  {t:"blank", id:"O4"},
  {t:"blank", id:"O5"},
  {t:"card", v:"grey", html:
    "<h4>The line, for contrast</h4>" +
    "<p class=\"txt\">{t:least_squares} line on the same three points: ŷ = 1.5 − 0.5 x. Train MSE = 0.5000. At x = 3 it predicts 0, squared error (0 − 0.5)² = 0.2500. At x = −1 it predicts 2, squared error (2 − 2.5)² = 0.2500. Mean test MSE = <b>0.2500</b>, against the quadratic's <b>30.2500</b>.</p>"},
  {t:"mcq", tag:"part 3 · question 3", answer:0,
   q:"Why is train MSE of the quadratic exactly zero?",
   opts:[
     {txt:"Three distinct x give three independent constraints, and three coefficients can meet all three.", hint:""},
     {txt:"Squared loss is always zero for polynomials.",
      hint:"A degree-0 polynomial on these points had train MSE 0.6667."},
     {txt:"The test points lie on the same quadratic.",
      hint:"ŷ(3) = −5, y = 0.5. They do not."},
     {txt:"Least squares always interpolates.",
      hint:"Only when the number of free parameters is at least N (and the basis can separate the points)."}],
   why:"This is the {t:interpolation_threshold} for this tiny problem: P = N = 3. Unique interpolator in this basis, and it is a bad predictor off the sample."},
  {t:"answer", html:"<p>Zero training loss is not a trophy. It is the definition of {t:interpolation}. Whether that interpolator {t:generalisation}s is a separate question, answered by test points — or, later, by which interpolator an overparameterised model selects.</p>"}
 ]},

{n:4, eyebrow:"part 4", cls:"your", title:"Bias, variance, noise — by hand",
 result:"E[(y − ŷ)²] = σ² + Bias² + Variance",
 blocks:[
  {t:"hook", q:"Same process, three different training sets. What, in the test error, is our fault?",
   hint:"μ = 5 is the true mean. σ² = 1 is given. We predict a constant."},
  {t:"p", html:"Bishop's decomposition (PRML §3.2; Deep Learning §4.3) is for {t:mse}. It splits expected test error into {t:irreducible_error}, {t:bias} squared, and {t:variance}. That sum is the {t:bias_variance}."},
  {t:"card", v:"navy", html:
    "<div class=\"eyebrow\">squared loss, one x</div>" +
    "<div class=\"mathline big\">E[(y − ŷ)²] = σ² + Bias² + Var</div>" +
    "<p class=\"txt\" style=\"margin:12px 0 0\">Bias = E<sub>D</sub>[ŷ] − f. &nbsp; Var = E<sub>D</sub>[(ŷ − E<sub>D</sub>[ŷ])²]. &nbsp; The three expectations are over training sets, then over y | x.</p>"},
  {t:"raw", html:"<div class=\"tbls\">" + T_BVDATA() + "</div>"},
  {t:"card", v:"grey", html: symbolTable("the three estimators", [
    ["A", "ignore the data. ŷ = 3 always. A cartoon of underfitting."],
    ["B", "copy the training y. ŷ ∈ {4, 6, 5}. Unbiased, jumpy."],
    ["C", "shrink toward 4: ŷ = ½ y + 2. A cartoon of regularisation."]
  ])},
  {t:"strip", pin:true, html:"μ = 5 &nbsp;&middot;&nbsp; σ² = 1 &nbsp;&middot;&nbsp; average over the three datasets with equal weight 1/3"},
  {t:"h3", html:"Model A · the stubborn constant"},
  {t:"blank", id:"B1"},
  {t:"blank", id:"B2"},
  {t:"blank", id:"B3"},
  {t:"blank", id:"B6"},
  {t:"h3", html:"Model B · copy the sample"},
  {t:"blanks", ids:["B4a","B4b"], need:["predictions 4, 6, 5"],
   prompt:"E[ŷ] = {{B4a}} &nbsp;&nbsp; Bias = {{B4b}}"},
  {t:"blank", id:"B5"},
  {t:"blank", id:"B7"},
  {t:"h3", html:"Model C · shrink"},
  {t:"note", html:"Predictions: ½·4+2 = 4.0, &nbsp; ½·6+2 = 5.0, &nbsp; ½·5+2 = 4.5. Mean 4.5, so Bias = 4.5 − 5 = −0.5, Bias² = 0.2500, Var = 0.1667, risk = 1.4167."},
  {t:"blank", id:"B8"},
  {t:"anim", id:"a3", title:"Animation 3 · redraw the training set",
   intro:"Left: many least-squares lines, one per redrawn sample of the sine. Right: many interpolating polynomials. The faint bundle is variance. The dashed mean curve versus the true sine is bias."},
  {t:"mcq", tag:"part 4 · question 4", answer:3,
   q:"Which change cuts variance without any hope of cutting bias to zero, if f is a sine and ŷ is a constant?",
   opts:[
     {txt:"Collect more training points, keep predicting a constant.",
      hint:"A constant's average will sit at the mean of the sine (near 0). Extra data reduces variance of that constant and leaves the bias."},
     {txt:"Set σ² = 0 by fiat.",
      hint:"You cannot legislate the noise. Also that term is not variance of ŷ."},
     {txt:"Switch to an interpolating polynomial of degree 9.",
      hint:"That usually raises variance. Look at animation 3."},
     {txt:"Neither more data nor a larger constant class: the class cannot contain a sine, so bias remains. More data still cuts this model's variance.", hint:""}],
   why:"The useful reading of {t:bias}: error that survives averaging over datasets. More data is not a substitute for a richer class when the class is wrong. It is a substitute for a jumpy estimator when the class is right."},
  {t:"answer", html:
    "<p>A: risk 5.0000, almost all bias. B: risk 1.6667, no bias, all the avoidable error is variance. C: risk 1.4167, a little bias bought a larger drop in variance. That last move is what {t:regularisation} is for.</p>"}
 ]},

{n:5, eyebrow:"part 5", title:"The U-shape, and where it stops being the whole story",
 result:"test error U-shape in the underparameterised regime is bias² + variance",
 blocks:[
  {t:"hook", q:"If we plot test error against capacity, why do we expect a U?",
   hint:"Bias falls, variance rises, σ² is a floor."},
  {t:"p", html:"Fix N. Grow {t:capacity}. Bias² typically falls (the class can match f). Variance typically rises (the class can also match the noise). Their sum is U-shaped. σ² does not care. That picture is the classical {t:bias_variance}."},
  {t:"anim", id:"a4", title:"Animation 4 · train versus test against degree",
   intro:"Degree on the horizontal axis. Amber: training MSE. Navy: test MSE against the true sine. The U is the test curve. Interpolation is the first degree where train hits ~ 0 (here degree 5, because N = 6)."},
  {t:"mcq", tag:"part 5 · question 5", answer:1,
   q:"On animation 4, what is the first degree at which training MSE hits (numerically) zero?",
   opts:[
     {txt:"Degree 0, because a constant can always fit six points.",
      hint:"A constant has one parameter. Six constraints. Animation 1 already showed a high training MSE."},
     {txt:"Degree 5: six coefficients, six points.", hint:""},
     {txt:"Degree 1, the line.",
      hint:"A line has two parameters. It will not interpolate six generic points."},
     {txt:"Never: squared loss cannot be zero.",
      hint:"Interpolation is exactly that: residuals zero, hence MSE zero."}],
   why:"P = M + 1. The {t:interpolation_threshold} for this basis is M + 1 = N, so M = 5. After that the unregularised polynomial is an interpolator with extra leftover degrees of freedom, and this particular basis becomes a wild extrapolator — which is why we need the next section."},
  {t:"card", v:"cream", html:
    "<h4>What the U-shape does not know</h4>" +
    "<p class=\"txt\">Classical plots stop near interpolation, or they add {t:weight_decay} and plot against λ. Modern deep nets sit far to the right: {t:overparameterised}, training loss ~ 0, and test loss often <em>better</em> than the U's minimum. That continuation is {t:double_descent}.</p>"},
  {t:"answer", html:"<p>Use the U-shape when you are still below interpolation, and when you are choosing λ. Do not use it to argue that a 100-million-parameter net must overfit merely because P ≫ N.</p>"}
 ]},

{n:6, eyebrow:"part 6", title:"Double descent",
 result:"test error can fall a second time after the interpolation peak",
 blocks:[
  {t:"hook", q:"If the model already interpolates, why would extra parameters help?",
   hint:"There are many interpolators. Extra parameters change which one you get."},
  {t:"p", html:"{t:double_descent} (Belkin et al. 2019; Nakkiran et al. 2020; Bishop & Bishop §9.3.2) is the empirical curve: test error descends as capacity grows, ascends into a peak at the {t:interpolation_threshold}, then descends again in the {t:overparameterised} regime. Prince (UDL §20.2) records the related fact that interpolating nets can still {t:generalisation} — even after {t:memorisation} of random labels is possible."},
  {t:"card", v:"navy", html:
    "<div class=\"eyebrow\">the peak is not the end</div>" +
    "<div class=\"mathline\">underparameterised U &nbsp; → &nbsp; interpolation peak &nbsp; → &nbsp; second descent</div>" +
    "<p class=\"txt\" style=\"margin:10px 0 0\">Train loss is ~ 0 everywhere to the right of the peak. The second descent is a statement about <em>which interpolator</em>, not about fitting the sample harder.</p>"},
  {t:"anim", id:"a5", title:"Animation 5 · a cartoon of double descent",
   intro:"Horizontal axis is parameter count P. Vertical is test error (log scale). The dotted line is P = N. Drag N to slide the interpolation peak. This is a schematic consistent with the papers, not a proof."},
  {t:"blank", id:"D1"},
  {t:"blank", id:"D2"},
  {t:"mcq", tag:"part 6 · question 6", answer:2,
   q:"A ResNet interpolates CIFAR-10 and still has low test error. What has failed?",
   opts:[
     {txt:"The definition of overfitting as train loss ≪ test loss. Gaps can still exist; they need not be catastrophic.",
      hint:"There often is a gap. The failed heuristic is 'P > N implies terrible test error'."},
     {txt:"Squared loss. Classification cannot overfit.",
      hint:"Cross-entropy interpolates too (zero training error / infinite likelihood on one-hot labels)."},
     {txt:"The heuristic that interpolation (or P > N) automatically means a useless test predictor.", hint:""},
     {txt:"The test set. It must overlap the train set.",
      hint:"Standard CIFAR splits do not. That is why the observation surprised people."}],
   why:"{t:overfitting} as 'the interpolator is always the worst test predictor' is the claim that died. {t:overfitting} as 'a gap between train and test' can still be true. Double descent says the gap's size is not monotone in P."},
  {t:"note", html:"{t:inductive_bias} of architecture plus the implicit bias of SGD are the usual explanations for which interpolator you get. This sheet does not derive that. It only insists you stop treating P > N as a proof of failure."},
  {t:"answer", html:"<p>Read a test curve in two halves. Left of P ≈ N: classical U, bias–variance. Right of P ≈ N: all interpolators, ranked by something other than training loss — often {t:effective_parameters}, {t:regularisation}, and the optimiser's path.</p>"}
 ]},

{n:7, eyebrow:"part 7", title:"Regularisation moves you along the curve",
 result:"λ, early stopping, and held-out data are how you choose a point on the curve",
 blocks:[
  {t:"hook", q:"You cannot always add parameters. What else shrinks variance?",
   hint:"Bishop's λ in the polynomial example."},
  {t:"p", html:"{t:regularisation} is a preference over functions inside a class that was already large. {t:weight_decay} is the cleanest: add λ‖θ‖². Large λ recovers a small {t:effective_parameters} count. {t:early_stopping} does a similar job in gradient descent. Tune them on a {t:validation_set}, not on the test set. Those choices are {t:hyperparameters}."},
  {t:"anim", id:"a6", title:"Animation 6 · ridge on a degree-9 polynomial",
   intro:"Same six points, M = 9, which would interpolate wildly at λ = 0. Raise λ and the wiggle dies. Too large, and you are back to underfitting."},
  {t:"blank", id:"R1"},
  {t:"mcq", tag:"part 7 · question 7", answer:0,
   q:"You report test accuracy after trying 40 values of λ and keeping the winner, all judged on the test set. The number you report is",
   opts:[
     {txt:"optimistically biased: the test set has been used as a validation set.", hint:""},
     {txt:"still unbiased, because θ was not updated on those examples.",
      hint:"θ was not, but λ was. Hyperparameter search overfits the split you select with."},
     {txt:"pessimistically biased, because λ extra-penalises.",
      hint:"Choosing the best of 40 test numbers overestimates future performance."},
     {txt:"exactly σ².",
      hint:"It is still a classification or regression score, not the noise variance."}],
   why:"Goodfellow §5.3 is blunt: once a split is used to make choices, it is a {t:validation_set}. You need a third split, or a fresh test, to claim {t:generalisation}."},
  {t:"answer", html:"<p>Practical summary. If training loss is high: you are under capacity, or λ is too big, or training is stuck. If training loss is low and test loss is high: you interpolated the sample; add regularisation, more data, or skip past the interpolation peak with a larger model plus a sane optimiser. Never tune that decision on the number you will publish.</p>"}
 ]},

{n:8, eyebrow:"retrieval", title:"Seven questions, no new arithmetic",
 result:"definitions, not tricks",
 blocks:[
  {t:"p", html:"Open any {t:underfitting} / {t:overfitting} / {t:bias} bubble if a word has gone cold."},
  {t:"mcq", tag:"retrieval · 1", answer:2,
   q:"High training loss and high test loss, similar to each other, most often indicates",
   opts:[
     {txt:"overfitting.", hint:"Overfitting is a large gap: train looks better than test."},
     {txt:"a corrupted test set only.", hint:"Train is also high. The class is failing on data it was allowed to fit."},
     {txt:"underfitting (or an unsolved optimisation problem).", hint:""},
     {txt:"double descent.", hint:"Double descent is a shape of test error versus scale, not a single (train, test) pair."}],
   why:"Same symptom as a constant on a sine: the model is not even winning on the sample."},
  {t:"mcq", tag:"retrieval · 2", answer:1,
   q:"Low training loss, much higher test loss, most often indicates",
   opts:[
     {txt:"underfitting.", hint:"Underfitting would not have produced a low training loss."},
     {txt:"overfitting (a large generalisation gap).", hint:""},
     {txt:"zero irreducible error.", hint:"σ² does not create a gap by itself."},
     {txt:"that P < N.", hint:"Interpolation overfitting typically needs P ≳ N, unless the basis is already unstable."}],
   why:"The definition you want: the sample was fitted, the process was not."},
  {t:"mcq", tag:"retrieval · 3", answer:0,
   q:"In the decomposition E[(y−ŷ)²] = σ² + Bias² + Var, which term cannot be removed by changing the hypothesis class?",
   opts:[
     {txt:"σ², the irreducible error.", hint:""},
     {txt:"Bias².", hint:"A richer class can reduce approximation error."},
     {txt:"Variance.", hint:"A smaller class, more data, or regularisation can reduce variance."},
     {txt:"None of them: all three are properties of ℋ only.", hint:"σ² is a property of y | x."}],
   why:"Even the Bayes predictor pays σ²."},
  {t:"mcq", tag:"retrieval · 4", answer:3,
   q:"An unbiased estimator of f (Bias = 0) can still have terrible test error because of",
   opts:[
     {txt:"σ² only. Variance of an unbiased estimator is always small.",
      hint:"Model B in part 4 was unbiased and had variance 0.6667."},
     {txt:"the validation set leaking.",
      hint:"The decomposition does not mention a validation set."},
     {txt:"double descent, exclusively.",
      hint:"The classical decomposition already has a variance term."},
     {txt:"variance (and σ²). Unbiasedness does not control how much ŷ jumps with D.", hint:""}],
   why:"Unbiased plus high variance is the interpolating polynomial on small N."},
  {t:"mcq", tag:"retrieval · 5", answer:1,
   q:"Double descent says that after the interpolation peak",
   opts:[
     {txt:"training loss rises again.", hint:"Training loss stays ~ 0. The second descent is in test error."},
     {txt:"test error can fall as P grows further.", hint:""},
     {txt:"bias and variance stop adding to MSE.", hint:"The identity still holds. The terms change with P."},
     {txt:"you no longer need a test set.", hint:"You need it more: training loss has become uninformative."}],
   why:"That is the content of Bishop & Bishop §9.3.2 and Nakkiran et al."},
  {t:"mcq", tag:"retrieval · 6", answer:2,
   q:"Weight decay λ ‖θ‖², as λ increases from 0, typically",
   opts:[
     {txt:"increases variance and decreases bias.",
      hint:"Shrinkage does the opposite: coefficients move less when D changes, and the average fit is pulled toward 0."},
     {txt:"changes σ².", hint:"The process does not know λ."},
     {txt:"decreases variance, at the cost of some extra bias.", hint:""},
     {txt:"forces interpolation.", hint:"Large λ prevents interpolation."}],
   why:"Model C was the discrete version of this move."},
  {t:"mcq", tag:"retrieval · 7", answer:0,
   q:"You should pick polynomial degree and λ on",
   opts:[
     {txt:"a validation set, then report a fresh test number once.", hint:""},
     {txt:"the training set, because that is what least squares uses.",
      hint:"Least squares already used the training set for θ. Using it again for M and λ is asking the sample to grade itself."},
     {txt:"the test set, to be honest about generalisation.",
      hint:"That number then stops being an honest test."},
     {txt:"whichever split has more examples, always.",
      hint:"Size matters, but role matters more: train / validate / test are different jobs."}],
   why:"Hyperparameters overfit the split you select them with. That split is then a {t:validation_set}."}
 ]}
];
