'use strict';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-US'),num=id=>Number($(id).value);
function matrix(title,data,n,selected=[]){return `<div class="matrix-group"><p>${title}</p><div class="matrix" role="img" aria-label="${title}: ${data.join(', ')}" style="--n:${n}">${data.map((v,i)=>`<span class="cell ${selected.includes(i)?'selected':''}">${v}</span>`).join('')}</div></div>`;}
function bars(id,rows){const max=Math.max(...rows.map(r=>r[1]));$(id).innerHTML=rows.map(([label,value],i)=>`<div class="bar-row"><div class="bar-label"><span>${label}</span><b>${fmt(value)} weights</b></div><div class="track"><div class="bar ${i?'secondary':''}" style="width:${100*value/max}%"></div></div></div>`).join('');}
function drawGradient(){const depth=num('depth'),g=CNN.gradient(depth,num('magnitude'));$('depth-value').textContent=depth;const w=Math.max(220,$('gradient-plot').clientWidth),h=260,left=48,right=15,top=20,bottom=48,scale=2.2,px=i=>left+i/(g.a.length-1)*(w-left-right),py=y=>top+(scale-y)/(2*scale)*(h-top-bottom);const path=a=>a.map((y,i)=>`${i?'L':'M'}${px(i).toFixed(2)},${py(y).toFixed(2)}`).join(' ');$('gradient-plot').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Synthetic paired gradient components; fixed vertical scale from minus two to plus two"><title>Synthetic paired gradient samples</title><rect x="${left}" y="${top}" width="${w-left-right}" height="${h-top-bottom}" fill="none" stroke="#cad5c8"/>${[-2,0,2].map(t=>`<text x="${left-8}" y="${py(t)+4}" text-anchor="end">${t}</text>`).join('')}<path d="M${left} ${py(0)}H${w-right}" stroke="#cad5c8"/><path d="${path(g.a)}" fill="none" stroke="#12655b" stroke-width="2.5"/><path d="${path(g.b)}" fill="none" stroke="#a9512c" stroke-width="2" stroke-dasharray="5 3"/><text x="${left}" y="${h-27}">1</text><text x="${w-right}" y="${h-27}" text-anchor="end">80</text><text x="${(left+w-right)/2}" y="${h-6}" text-anchor="middle">Paired sample index</text><text transform="translate(14 ${h/2}) rotate(-90)" text-anchor="middle">Gradient value</text></svg><p class="caption">Solid teal: g(x) samples · dashed rust: paired g(x + δ) samples</p>`;$('gradient-result').innerHTML=`Correlation <strong>${CNN.correlate(g.a,g.b).toFixed(3)}</strong> &nbsp; · &nbsp; RMS of each trace <strong>${g.rms.toFixed(2)}</strong><br>Change depth to alter agreement; change magnitude to shrink both traces without changing their correlation.`;}
function drawResidual(){const a=num('res-a'),r=CNN.residual(a);$('res-a-value').textContent=a.toFixed(1);$('residual-values').innerHTML=`<div><b>PLAIN · y = ax</b><p>Output <strong>${r.plain.toFixed(1)}</strong></p><p>dy/dx = ${r.plainGradient.toFixed(1)}</p></div><div><b>RESIDUAL · y = x + ax</b><p>Output <strong>${r.residual.toFixed(1)}</strong></p><p>dy/dx = 1 + (${a.toFixed(1)}) = ${r.residualGradient.toFixed(1)}</p></div>`;$('residual-matrices').innerHTML=matrix('Input x',[2,1,0,3],2)+matrix('Correction F(x) = ax',[2,1,0,3].map(v=>(v*a).toFixed(1)),2)+matrix('Sum x + F(x)',[2,1,0,3].map(v=>(v*(1+a)).toFixed(1)),2);}
function drawShape(){const s=CNN.shape($('stage').value==='transition',$('shortcut').value==='projection');$('shape-result').innerHTML=`<strong class="${s.valid?'':'error'}">${s.valid?'Addition is valid.':'Shape mismatch: addition is invalid.'}</strong><br>Main route: ${s.output}. Shortcut: ${s.shortcut}.<br>${s.projectionWeights?`Projection: ${fmt(s.projectionWeights)} convolution weights.`:'Identity shortcut: 0 parameters.'}${!s.valid?' Choose a projection to align both routes.':''}`;$('shape-bars').innerHTML=`<span>Input ${s.input}</span><span>F(x): ${s.output}</span><span>P(x): ${s.shortcut}</span><span>${s.valid?'Add → ReLU → '+s.output:'Cannot add these shapes'}</span>`;}
function drawInception(){const r=num('bottleneck'),b=CNN.branch(r),saving=100*(1-b.reduced/b.direct);$('bottleneck-value').textContent=r;$('inception-result').innerHTML=`Direct: 9 × 192 × 128 = <strong>${fmt(b.direct)}</strong><br>With reduction: 192 × ${r} + 9 × ${r} × 128 = <strong>${fmt(b.reduced)}</strong><br>${saving>=0?saving.toFixed(1)+'% fewer':(-saving).toFixed(1)+'% more'} weights. Output remains 28 × 28 × 128 for this branch.`;bars('inception-bars',[['Direct 3 × 3',b.direct],['1 × 1 reduction + 3 × 3',b.reduced]]);const size=num('window'),radius=(size-1)/2,selected=[];for(let i=0;i<25;i++)if(Math.abs(Math.floor(i/5)-2)<=radius&&Math.abs(i%5-2)<=radius)selected.push(i);$('window-matrix').innerHTML=matrix(`${size} × ${size} support centered at row 3, column 3`,[0,0,1,0,0,0,2,3,2,0,1,3,9,3,1,0,2,3,2,0,0,0,1,0,0],5,selected);}
const channelA=[1,2,3,4,5,6,7,8,9],channelB=[9,8,7,6,5,4,3,2,1],dwA=CNN.conv2(channelA),dwB=CNN.conv2(channelB);
function drawDepthwise(){const k=num('kernel'),m=num('channels-in'),n=num('channels-out'),c=CNN.costs(k,m,n);$('depthwise-result').innerHTML=`Standard <strong>${fmt(c.standard)}</strong> &nbsp; · &nbsp; Separable <strong>${fmt(c.separable)}</strong> weights<br>Depthwise ${fmt(c.depthwise)} + pointwise ${fmt(c.pointwise)}. Ratio ${c.ratio.toFixed(4)} (${(c.ratio*100).toFixed(2)}% of standard).<br>${c.ratio<1?(1/c.ratio).toFixed(2)+'× fewer weights':(c.ratio).toFixed(2)+'× as many weights; no saving here.'}<br>At 28 × 28 output: ${fmt(c.standardMAC)} vs ${fmt(c.separableMAC)} MACs.`;bars('depthwise-bars',[['Standard convolution',c.standard],['Depthwise + pointwise',c.separable]]);const index=num('pixel'),start=[0,1,3,4][index],patch=[start,start+1,start+3,start+4];$('depthwise-matrices').innerHTML=matrix('Input channel A',channelA,3,patch)+matrix('Input channel B',channelB,3,patch)+matrix('Depthwise A′',dwA,2,[index])+matrix('Depthwise B′',dwB,2,[index])+matrix('Pointwise: A′ − B′',dwA.map((v,i)=>v-dwB[i]),2,[index]);$('pixel-result').innerHTML=`A′ = ${patch.map(i=>channelA[i]).join(' + ')} = <b>${dwA[index]}</b><br>B′ = ${patch.map(i=>channelB[i]).join(' + ')} = <b>${dwB[index]}</b><br>Pointwise output = 1 × ${dwA[index]} + (−1) × ${dwB[index]} = <strong>${dwA[index]-dwB[index]}</strong>`;}
for(const [ids,fn] of [[['depth','magnitude'],drawGradient],[['res-a'],drawResidual],[['stage','shortcut'],drawShape],[['bottleneck','window'],drawInception],[['kernel','channels-in','channels-out','pixel'],drawDepthwise]]){ids.forEach(id=>$(id).addEventListener('input',fn));fn();}
if(typeof ResizeObserver!=='undefined')new ResizeObserver(drawGradient).observe($('gradient-plot'));
const key='cnn-architectures-responses-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};if(typeof saved!=='object'||Array.isArray(saved))saved={};}catch{$('save-note').textContent='Browser storage unavailable. Download your responses before closing.';}
for(const el of document.querySelectorAll('textarea')){el.value=typeof saved[el.id]==='string'?saved[el.id]:'';el.addEventListener('input',()=>{saved[el.id]=el.value;try{localStorage.setItem(key,JSON.stringify(saved));}catch{$('save-note').textContent='Could not save here. Download your responses before closing.';}});}
$('print').addEventListener('click',()=>window.print());
$('download-notes').addEventListener('click',()=>{const content=['# CNN architectures — my responses',...Array.from(document.querySelectorAll('textarea')).map(el=>`\n## ${document.querySelector('label[for="'+el.id+'"]').textContent}\n\n${el.value||'(No response)'}`)].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download='cnn-architectures-responses.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});

// Mirror the foundation worksheet's current-section navigation.
const sectionLinks=Array.from(document.querySelectorAll('.sidebar nav a'));
const lectureSections=sectionLinks.map(link=>document.querySelector(link.getAttribute('href')));
let sectionFrame=0;
function markCurrentSection(){
  sectionFrame=0;
  let current=lectureSections[0];
  for(const section of lectureSections)if(section.getBoundingClientRect().top<=180)current=section;
  for(const link of sectionLinks){const active=link.getAttribute('href')==='#'+current.id;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');}
}
addEventListener('scroll',()=>{if(!sectionFrame)sectionFrame=requestAnimationFrame(markCurrentSection);},{passive:true});
markCurrentSection();
