const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('./model.js');
test('separable counts and MACs match hand calculation',()=>{const c=M.costs(3,32,64);assert.equal(c.standard,18432);assert.equal(c.depthwise,288);assert.equal(c.pointwise,2048);assert.equal(c.separable,2336);assert.equal(c.standardMAC,14450688);assert.equal(c.separableMAC,1831424);assert.ok(Math.abs(c.ratio-(1/64+1/9))<1e-12);});
test('degenerate cases do not claim savings',()=>{assert.ok(M.costs(1,32,64).ratio>1);assert.ok(M.costs(3,32,1).ratio>1);});
test('exit challenge counts',()=>{assert.equal(M.costs(3,64,128).standard,73728);assert.equal(M.costs(3,64,128).separable,8768);});
test('Inception bottleneck can save or increase cost',()=>{assert.deepEqual(M.branch(96),{direct:221184,reduced:129024});assert.equal(M.branch(176).reduced,236544);assert.ok(M.branch(176).reduced>M.branch(176).direct);});
test('identity preserves at zero and cancellation remains possible',()=>{assert.deepEqual(M.residual(0),{plain:0,residual:2,plainGradient:0,residualGradient:1});assert.equal(M.residual(-1).residualGradient,0);});
test('projection repairs stage-boundary shape mismatch',()=>{assert.equal(M.shape(true,false).valid,false);assert.equal(M.shape(true,true).valid,true);assert.equal(M.shape(true,true).projectionWeights,8192);assert.equal(M.shape(false,false).valid,true);});
test('synthetic correlation changes independently of magnitude',()=>{for(const depth of [1,4,16,32])for(const magnitude of [1,.05]){const g=M.gradient(depth,magnitude);assert.ok(Math.abs(M.correlate(g.a,g.b)-g.rho)<1e-12);for(const trace of [g.a,g.b])assert.ok(Math.abs(Math.sqrt(trace.reduce((s,v)=>s+v*v,0)/trace.length)-magnitude)<1e-12);}});
test('exact depthwise example and pointwise combination',()=>{const a=M.conv2([1,2,3,4,5,6,7,8,9]),b=M.conv2([9,8,7,6,5,4,3,2,1]);assert.deepEqual(a,[12,16,24,28]);assert.deepEqual(b,[28,24,16,12]);assert.deepEqual(a.map((v,i)=>v-b[i]),[-16,-8,8,16]);});
