const {test}=require('node:test'),assert=require('node:assert/strict');
const {createPlayer}=require('./timeline');
function setup(reduced=false){let next=null,id=0;const frames=[];const p=createPlayer([{},{checkpoint:true},{}],s=>frames.push(s),{transition:100,hold:200,reduced:()=>reduced,request:f=>{next=f;return ++id},cancel:()=>{next=null}});return {p,frames,tick(t){const f=next;next=null;if(f)f(t);},pending:()=>!!next};}
test('play pauses on a prediction before revealing its answer',()=>{const c=setup();c.p.play();[0,200,300,400].forEach(c.tick);assert.equal(c.p.state.index,1);assert.equal(c.p.state.progress,1);assert.equal(c.p.state.playing,false);assert.equal(c.p.state.checkpoint,true);assert.equal(c.pending(),false);c.p.play();[500,600,800].forEach(c.tick);assert.equal(c.p.state.index,2);assert.equal(c.p.state.playing,false);});
test('manual next animates then settles; pausing and seeking cancel pending work',()=>{const c=setup();c.p.next();c.tick(0);c.tick(50);assert.equal(c.p.state.progress,.5);c.p.pause();assert.equal(c.pending(),false);c.p.seek(1.25);assert.equal(c.p.state.index,2);assert.equal(c.p.state.progress,.25);assert.equal(c.pending(),false);c.p.restart();assert.equal(c.p.state.index,0);assert.equal(c.p.state.progress,1);});
test('speed changes time progression and replay resets the end',()=>{const c=setup();c.p.next();c.p.speed(2);c.tick(0);c.tick(25);assert.equal(c.p.state.progress,.5);c.p.seek(2);c.p.play();assert.equal(c.p.state.index,0);assert.equal(c.p.state.playing,true);c.p.destroy();assert.equal(c.pending(),false);});
test('reduced motion exposes stable frames without a running animation',()=>{const c=setup(true);c.p.play();assert.equal(c.p.state.index,1);assert.equal(c.p.state.progress,1);assert.equal(c.pending(),false);c.p.play();assert.equal(c.p.state.index,2);assert.equal(c.pending(),false);});
test('long pixel motions use their planned duration rather than the default',()=>{
 let tick;const p=createPlayer([{}, {transition:4200}],()=>{}, {request:f=>{tick=f;return 1;},cancel:()=>{tick=null;}});p.next();tick(0);tick(2100);assert.equal(p.state.progress,.5);tick(4200);assert.equal(p.state.progress,1);assert.equal(p.state.playing,false);
});
